// hsk-data.js (đã làm sạch + bổ sung ví dụ/dịch HSK1+HSK2+HSK3+HSK4+HSK5)
// Cấu trúc: [hanzi, pinyin, meaning, ex_hanzi, ex_pinyin, ex_viet, tu_loai]

const _HSK_RAW = {
  "hsk1": [
   ["最高管理", "zuì gāo guǎn lǐ", "quản lý cấp cao nhất", "公司实行最高管理层负责制。", "Gōngsī shíxíng zuìgāo guǎnlǐcéng fùzé zhì.", "Công ty thực hiện chế độ chịu trách nhiệm của ban quản lý cấp cao nhất.", "Danh từ"],
  ["决策机构", "jué cè jī gòu", "cơ quan ra quyết định", "董事会是公司的决策机构。", "Dǒngshìhuì shì gōngsī de juécè jīgòu.", "Hội đồng quản trị là cơ quan ra quyết định của công ty.", "Danh từ"],
  ["董事会", "dǒng shì huì", "hội đồng quản trị", "董事会定期开会讨论公司的重要问题。", "Dǒngshìhuì dìngqī kāihuì tǎolùn gōngsī de zhòngyào wèntí.", "Hội đồng quản trị họp định kỳ để thảo luận các vấn đề quan trọng của công ty.", "Danh từ"],
  ["总经理办公室", "zǒng jīng lǐ bàn gōng shì", "văn phòng tổng giám đốc", "总经理办公室负责公司的日常工作。", "Zǒngjīnglǐ bàngōngshì fùzé gōngsī de rìcháng gōngzuò.", "Văn phòng tổng giám đốc chịu trách nhiệm các công việc thường ngày của công ty.", "Danh từ"],
  ["战略决策", "zhàn lüè jué cè", "quyết định chiến lược", "公司需要根据市场的变化做出战略决策。", "Gōngsī xūyào gēnjù shìchǎng de biànhuà zuòchū zhànlüè juécè.", "Công ty cần đưa ra quyết định chiến lược dựa trên sự thay đổi của thị trường.", "Danh từ"],
  ["整体管理", "zhěng tǐ guǎn lǐ", "quản lý tổng thể", "总经理负责公司的整体管理工作。", "Zǒngjīnglǐ fùzé gōngsī de zhěngtǐ guǎnlǐ gōngzuò.", "Tổng giám đốc phụ trách công tác quản lý tổng thể của công ty.", "Danh từ"],
  ["跨部门", "kuà bù mén", "liên phòng ban / liên bộ phận", "项目的成功离不开跨部门的合作。", "Xiàngmù de chénggōng lí bù kāi kuà bùmén de hézuò.", "Sự thành công của dự án không thể thiếu sự hợp tác giữa các phòng ban.", "Tính từ"],
  ["协调", "xié tiáo", "điều phối, phối hợp", "各部门需要加强沟通与协调。", "Gè bùmén xūyào jiāqiáng gōutōng yǔ xiétiáo.", "Các phòng ban cần tăng cường giao tiếp và phối hợp với nhau.", "Động từ"],
  ["报到", "bàodào", "báo danh, trình diện", "新员工到人事部报到。今天我到公司报到。", "Xīn yuángōng dào rénshìbù bàodào. Jīntiān wǒ dào gōngsī bàodào.", "Nhân viên mới đến phòng nhân sự để báo danh. Hôm nay tôi đến công ty để trình diện.", "Động từ"],
  ["人事专员", "rénshì zhuānyuán", "chuyên viên nhân sự", "人事专员负责接待新员工。我第一天见到了人事专员。", "Rénshì zhuānyuán fùzé jiēdài xīn yuángōng. Wǒ dì yì tiān jiàndào le rénshì zhuānyuán.", "Chuyên viên nhân sự phụ trách tiếp đón nhân viên mới. Tôi đã gặp chuyên viên nhân sự vào ngày đầu tiên.", "Danh từ"],
  ["接待", "jiēdài", "tiếp đón", "人事部接待新员工。公司派人来接待客户。", "Rénshìbù jiēdài xīn yuángōng. Gōngsī pài rén lái jiēdài kèhù.", "Bộ phận nhân sự tiếp đón nhân viên mới. Công ty cử người đến tiếp đón khách hàng.", "Động từ"],
  ["介绍", "jièshào", "giới thiệu", "他们向新员工介绍公司。我想介绍我们的公司。", "Tāmen xiàng xīn yuángōng jièshào gōngsī. Wǒ xiǎng jièshào wǒmen de gōngsī.", "Họ giới thiệu về công ty cho nhân viên mới. Tôi muốn giới thiệu công ty của chúng tôi.", "Động từ"],
  ["组织架构", "zǔzhī jiàgòu", "cơ cấu tổ chức", "公司有清晰的组织架构。我需要了解公司的组织架构。", "Gōngsī yǒu qīngxī de zǔzhī jiàgòu. Wǒ xūyào liǎojiě gōngsī de zǔzhī jiàgòu.", "Công ty có cơ cấu tổ chức rõ ràng. Tôi cần hiểu cơ cấu tổ chức của công ty.", "Danh từ"],
  ["职能", "zhínéng", "chức năng, nhiệm vụ", "每个部门有不同的职能。你知道这个部门的职能吗？", "Měi gè bùmén yǒu bùtóng de zhínéng. Nǐ zhīdào zhège bùmén de zhínéng ma?", "Mỗi bộ phận có chức năng khác nhau. Bạn có biết chức năng của bộ phận này không?", "Danh từ"],
  ["负责人", "fùzérén", "người phụ trách", "我想见这个部门的负责人。谁是这项工作的负责人？", "Wǒ xiǎng jiàn zhège bùmén de fùzérén. Shuí shì zhè xiàng gōngzuò de fùzérén?", "Tôi muốn gặp người phụ trách bộ phận này. Ai là người phụ trách công việc này?", "Danh từ"],
  ["生产计划部", "shēngchǎn jìhuà bù", "bộ phận kế hoạch sản xuất", "我想向生产计划部询问生产计划。", "Wǒ xiǎng xiàng shēngchǎn jìhuà bù xúnwèn shēngchǎn jìhuà.", "Tôi muốn hỏi kế hoạch sản xuất với bộ phận kế hoạch sản xuất.", "Danh từ"],
  ["生产部", "shēngchǎn bù", "bộ phận sản xuất", "生产部负责生产产品。", "Shēngchǎn bù fùzé shēngchǎn chǎnpǐn.", "Bộ phận sản xuất phụ trách việc sản xuất sản phẩm.", "Danh từ"],
  ["制定", "zhìdìng", "xây dựng, soạn thảo", "公司正在制定新计划。", "Gōngsī zhèngzài zhìdìng xīn jìhuà.", "Công ty đang xây dựng kế hoạch mới.", "Động từ"],
  ["生产计划", "shēngchǎn jìhuà", "kế hoạch sản xuất", "我们需要制定详细的生产计划。", "Wǒmen xūyào zhìdìng xiángxì de shēngchǎn jìhuà.", "Chúng tôi cần lập kế hoạch sản xuất chi tiết.", "Danh từ"],
  ["协调", "xiétiáo", "điều phối, phối hợp", "协调物料与进度很重要。", "Xiétiáo wùliào yǔ jìndù hěn zhòngyào.", "Việc phối hợp nguyên liệu và tiến độ rất quan trọng.", "Động từ"],
  ["物料", "wùliào", "nguyên liệu", "缺少物料会影响生产进度。", "Quēshǎo wùliào huì yǐngxiǎng shēngchǎn jìndù.", "Thiếu nguyên liệu sẽ ảnh hưởng đến tiến độ sản xuất.", "Danh từ"],
  ["进度", "jìndù", "tiến độ", "我们需要严格控制生产进度。", "Wǒmen xūyào yángé kòngzhì shēngchǎn jìndù.", "Chúng ta cần kiểm soát chặt chẽ tiến độ sản xuất.", "Danh từ"],
  ["确保", "quèbǎo", "đảm bảo", "确保按时交货是我们的目标。", "Quèbǎo ànshí jiāohuò shì wǒmen de mùbiāo.", "Đảm bảo giao hàng đúng hạn là mục tiêu của chúng tôi.", "Động từ"],
  ["订单", "dìngdān", "đơn hàng", "订单数量比上个月多。", "Dìngdān shùliàng bǐ shàng gè yuè duō.", "Số lượng đơn hàng nhiều hơn tháng trước.", "Danh từ"],
  ["实际生产操作", "shíjì shēngchǎn cāozuò", "thao tác sản xuất thực tế", "他们负责产品的实际生产操作。", "Tāmen fùzé chǎnpǐn de shíjì shēngchǎn cāozuò.", "Họ phụ trách thao tác sản xuất thực tế của sản phẩm.", "Danh từ"],
  ["生产人员管理", "shēngchǎn rényuán guǎnlǐ", "quản lý nhân viên sản xuất", "生产部也负责生产人员管理。", "Shēngchǎn bù yě fùzé shēngchǎn rényuán guǎnlǐ.", "Bộ phận sản xuất cũng phụ trách quản lý nhân viên sản xuất.", "Danh từ"],
  ["技术支持", "jìshù zhīchí", "hỗ trợ kỹ thuật", "技术部提供技术支持。", "Jìshùbù tígōng jìshù zhīchí.", "Bộ phận kỹ thuật cung cấp hỗ trợ kỹ thuật.", "Danh từ"],
  ["工艺改进", "gōngyì gǎijìn", "cải tiến quy trình công nghệ", "我们不断推进工艺改进。", "Wǒmen búduàn tuījìn gōngyì gǎijìn.", "Chúng tôi luôn thúc đẩy cải tiến quy trình công nghệ.", "Danh từ"],
  ["工程部", "gōngchéng bù", "bộ phận kỹ thuật / phòng kỹ thuật", "工程部负责技术管理。", "Gōngchéngbù fùzé jìshù guǎnlǐ.", "Bộ phận kỹ thuật chịu trách nhiệm quản lý kỹ thuật.", "Danh từ"],  ["技术部", "jìshù bù", "bộ phận kỹ thuật / phòng kỹ thuật", "技术问题由技术部处理。", "Jìshù wèntí yóu jìshùbù chǔlǐ.", "Các vấn đề kỹ thuật do bộ phận kỹ thuật xử lý.", "Danh từ"],
  ["图纸管理", "túzhǐ guǎnlǐ", "quản lý bản vẽ", "我们实行严格的图纸管理。", "Wǒmen shíxíng yángé de túzhǐ guǎnlǐ.", "Chúng tôi thực hiện quản lý bản vẽ nghiêm ngặt.", "Danh từ"],
  ["研发部", "yánfā bù", "bộ phận nghiên cứu và phát triển", "研发部负责技术创新。", "Yánfābù fùzé jìshù chuàngxīn.", "Bộ phận nghiên cứu và phát triển phụ trách đổi mới công nghệ.", "Danh từ"],
  ["新产品设计", "xīn chǎnpǐn shèjì", "thiết kế sản phẩm mới", "研发部负责新产品设计。", "Yánfābù fùzé xīn chǎnpǐn shèjì.", "Bộ phận R&D chịu trách nhiệm thiết kế sản phẩm mới.", "Danh từ"],
  ["样品开发", "yàngpǐn kāifā", "phát triển mẫu", "我们在量产前进行样品开发。", "Wǒmen zài liàngchǎn qián jìnxíng yàngpǐn kāifā.", "Chúng tôi tiến hành phát triển mẫu trước khi sản xuất hàng loạt.", "Danh từ"],
  ["技术创新", "jìshù chuàngxīn", "đổi mới kỹ thuật", "技术创新是提升竞争力的关键。", "Jìshù chuàngxīn shì tíshēng jìngzhēnglì de guānjiàn.", "Đổi mới kỹ thuật là chìa khóa nâng cao năng lực cạnh tranh.", "Danh từ"],
  ["负责", "fùzé", "phụ trách, chịu trách nhiệm", "他负责公司的技术工作。", "Tā fùzé gōngsī de jìshù gōngzuò.", "Anh ấy phụ trách mảng kỹ thuật của công ty.", "Động từ"],
  ["推进", "tuījìn", "thúc đẩy, đẩy mạnh", "我们将按进度推进项目。", "Wǒmen jiāng àn jìndù tuījìn xiàngmù.", "Chúng tôi sẽ thúc đẩy dự án theo tiến độ.", "Động từ"],
  ["品质部", "pǐnzhì bù", "bộ phận chất lượng", "品质部负责产品质量管理。", "Pǐnzhìbù fùzé chǎnpǐn zhìliàng guǎnlǐ.", "Bộ phận chất lượng chịu trách nhiệm quản lý chất lượng sản phẩm.", "Danh từ"],
  ["QA/QC", "QA/QC", "kiểm soát chất lượng (đảm bảo chất lượng)", "QA/QC确保产品符合客户要求。", "QA/QC quèbǎo chǎnpǐn fúhé kèhù yāoqiú.", "QA/QC đảm bảo sản phẩm đáp ứng yêu cầu của khách hàng.", "Danh từ"],
  ["来料检验", "láiliào jiǎnyàn", "kiểm tra nguyên liệu đầu vào", "我们对所有来料进行检验。", "Wǒmen duì suǒyǒu láiliào jìnxíng jiǎnyàn.", "Chúng tôi kiểm tra tất cả nguyên liệu đầu vào.", "Danh từ"],
  ["制程品质控制", "zhìchéng pǐnzhì kòngzhì", "kiểm soát chất lượng trong quá trình sản xuất", "制程品质控制非常重要。", "Zhìchéng pǐnzhì kòngzhì fēicháng zhòngyào.", "Kiểm soát chất lượng trong quá trình sản xuất là rất quan trọng.", "Danh từ"],
  ["出货检验", "chūhuò jiǎnyàn", "kiểm tra hàng xuất kho", "货物出货前必须进行出货检验。", "Huòwù chūhuò qián bìxū jìnxíng chūhuò jiǎnyàn.", "Hàng hóa phải được kiểm tra trước khi xuất kho.", "Danh từ"],
  ["确保", "quèbǎo", "đảm bảo", "我们确保产品符合客户要求。", "Wǒmen quèbǎo chǎnpǐn fúhé kèhù yāoqiú.", "Chúng tôi đảm bảo sản phẩm đáp ứng yêu cầu của khách hàng.", "Động từ"],
  ["产品", "chǎnpǐn", "sản phẩm", "我们的产品质量稳定。", "Wǒmen de chǎnpǐn zhìliàng wěndìng.", "Sản phẩm của chúng tôi có chất lượng ổn định.", "Danh từ"],
  ["符合", "fúhé", "phù hợp", "产品必须符合国际标准。", "Chǎnpǐn bìxū fúhé guójì biāozhǔn.", "Sản phẩm phải phù hợp với các tiêu chuẩn quốc tế.", "Động từ"],
  ["客户", "kèhù", "khách hàng", "客户的满意是我们的目标。", "Kèhù de mǎnyì shì wǒmen de mùbiāo.", "Sự hài lòng của khách hàng là mục tiêu của chúng tôi.", "Danh từ"],
  ["体系要求", "tǐxì yāoqiú", "yêu cầu hệ thống (tiêu chuẩn hệ thống)", "我们遵守质量管理体系要求。", "Wǒmen zūnshǒu zhìliàng guǎnlǐ tǐxì yāoqiú.", "Chúng tôi tuân thủ các yêu cầu của hệ thống quản lý chất lượng.", "Danh từ"],
  ["采购部", "cǎigòu bù", "bộ phận mua hàng", "采购部负责采购原材料。", "Cǎigòubù fùzé cǎigòu yuáncáiliào.", "Bộ phận mua hàng phụ trách mua nguyên vật liệu.", "Danh từ"],
  ["原材料", "yuáncáiliào", "nguyên vật liệu", "公司需要采购高质量的原材料。", "Gōngsī xūyào cǎigòu gāozhìliàng de yuáncáiliào.", "Công ty cần mua nguyên vật liệu chất lượng cao.", "Danh từ"],
  ["零件", "língjiàn", "linh kiện", "我们从国外进口零件。", "Wǒmen cóng guówài jìnkǒu língjiàn.", "Chúng tôi nhập khẩu linh kiện từ nước ngoài.", "Danh từ"],
  ["采购", "cǎigòu", "mua sắm", "公司进行设备采购。", "Gōngsī jìnxíng shèbèi cǎigòu.", "Công ty tiến hành mua sắm thiết bị.", "Động từ"],
  ["服务", "fúwù", "dịch vụ", "公司为客户提供优质服务。", "Gōngsī wèi kèhù tígōng yōuzhì fúwù.", "Công ty cung cấp dịch vụ tốt cho khách hàng.", "Danh từ"],
  ["仓储", "cāngchǔ", "lưu kho", "这个部门负责货物仓储。", "Zhège bùmén fùzé huòwù cāngchǔ.", "Bộ phận này chịu trách nhiệm lưu kho hàng hóa.", "Danh từ"],
  ["物料", "wùliào", "vật liệu", "需要有效管理仓库里的物料。", "Xūyào yǒuxiào guǎnlǐ cāngkù lǐ de wùliào.", "Cần quản lý vật liệu trong kho hiệu quả.", "Danh từ"],
  ["库存管理", "kùcún guǎnlǐ", "quản lý tồn kho", "公司采用现代化的库存管理系统。", "Gōngsī cǎiyòng xiàndàihuà de kùcún guǎnlǐ xìtǒng.", "Công ty áp dụng hệ thống quản lý tồn kho hiện đại.", "Danh từ"],
  ["发货", "fāhuò", "giao hàng", "今天我们会按时发货。", "Jīntiān wǒmen huì ànshí fāhuò.", "Hôm nay chúng tôi sẽ giao hàng đúng hạn.", "Động từ"],
  ["运输安排", "yùnshū ānpái", "sắp xếp vận chuyển", "物流部负责运输安排。", "Wùliúbù fùzé yùnshū ānpái.", "Bộ phận logistics phụ trách sắp xếp vận chuyển.", "Danh từ"],
  ["财务部", "cáiwù bù", "bộ phận tài chính", "财务部管理公司的费用。", "Cáiwùbù guǎnlǐ gōngsī de fèiyòng.", "Bộ phận tài chính quản lý chi phí của công ty.", "Danh từ"],
  ["财务管理", "cáiwù guǎnlǐ", "quản lý tài chính", "公司需要进行有效的财务管理。", "Gōngsī xūyào jìnxíng yǒuxiào de cáiwù guǎnlǐ.", "Công ty cần quản lý tài chính hiệu quả.", "Danh từ"],
  ["成本核算", "chéngběn hésuàn", "tính toán chi phí", "我们进行生产成本核算。", "Wǒmen jìnxíng shēngchǎn chéngběn hésuàn.", "Chúng tôi tiến hành tính toán chi phí sản xuất.", "Danh từ"],
  ["税务", "shuìwù", "thuế vụ", "公司必须遵守税务规定。", "Gōngsī bìxū zūnshǒu shuìwù guīdìng.", "Công ty phải tuân thủ quy định về thuế.", "Danh từ"],
  ["信息技术部", "xìnxī jìshù bù", "bộ phận công nghệ thông tin", "信息技术部管理公司的系统。", "Xìnxī jìshù bù guǎnlǐ gōngsī de xìtǒng.", "Bộ phận CNTT quản lý hệ thống công ty.", "Danh từ"],
  ["系统", "xìtǒng", "hệ thống", "系统需要经常升级。", "Xìtǒng xūyào jīngcháng shēngjí.", "Hệ thống cần được nâng cấp thường xuyên.", "Danh từ"],
  ["网络", "wǎngluò", "mạng", "内部网络必须稳定安全。", "Nèibù wǎngluò bìxū wěndìng ānquán.", "Mạng nội bộ phải ổn định và an toàn.", "Danh từ"],
  ["数据安全", "shùjù ānquán", "an toàn dữ liệu", "公司注重数据安全。", "Gōngsī zhùzhòng shùjù ānquán.", "Công ty chú trọng bảo mật dữ liệu.", "Danh từ"],
  ["负责", "fùzé", "phụ trách", "这个部门主要负责这项工作。", "Zhège bùmén zhǔyào fùzé zhè xiàng gōngzuò.", "Bộ phận này chịu trách nhiệm chính về công việc.", "Động từ"],
  ["管理", "guǎnlǐ", "quản lý", "良好的管理有助于提高工作效率。", "Liánghǎo de guǎnlǐ yǒuzhùyú tígāo gōngzuò xiàolǜ.", "Quản lý tốt giúp nâng cao hiệu quả công việc.", "Động từ"],
  ["设备维修部", "shèbèi wéixiū bù", "bộ phận bảo trì thiết bị", "设备维修部负责维修机器。", "Shèbèi wéixiū bù fùzé wéixiū jīqì.", "Bộ phận bảo trì thiết bị phụ trách sửa chữa máy móc.", "Danh từ"],
  ["设备", "shèbèi", "thiết bị", "设备需要经常保养。", "Shèbèi xūyào jīngcháng bǎoyǎng.", "Thiết bị cần được bảo dưỡng thường xuyên.", "Danh từ"],
  ["保养", "bǎoyǎng", "bảo dưỡng", "设备必须定期保养。", "Shèbèi bìxū dìngqī bǎoyǎng.", "Thiết bị phải được bảo dưỡng định kỳ.", "Động từ"],
  ["维修", "wéixiū", "sửa chữa", "技术员正在维修设备。", "Jìshùyuán zhèngzài wéixiū shèbèi.", "Kỹ thuật viên đang sửa chữa thiết bị.", "Động từ"],
  ["环境、健康与安全部", "huánjìng, jiànkāng yǔ ānquán bù", "bộ phận môi trường, sức khỏe và an toàn", "环境、健康与安全部负责许多重要工作。", "Huánjìng, jiànkāng yǔ ānquán bù fùzé xǔduō zhòngyào gōngzuò.", "Bộ phận EHS phụ trách nhiều công việc quan trọng.", "Danh từ"],
  ["安全生产", "ānquán shēngchǎn", "an toàn sản xuất", "公司始终确保安全生产。", "Gōngsī shǐzhōng quèbǎo ānquán shēngchǎn.", "Công ty luôn đảm bảo an toàn sản xuất.", "Danh từ"],
  ["环境保护", "huánjìng bǎohù", "bảo vệ môi trường", "我们注重环境保护。", "Wǒmen zhùzhòng huánjìng bǎohù.", "Chúng tôi chú trọng bảo vệ môi trường.", "Danh từ"],
  ["员工健康管理", "yuángōng jiànkāng guǎnlǐ", "quản lý sức khỏe nhân viên", "公司有员工健康管理计划。", "Gōngsī yǒu yuángōng jiànkāng guǎnlǐ jìhuà.", "Công ty có chương trình quản lý sức khỏe nhân viên.", "Danh từ"],
  ["生产设备", "shēngchǎn shèbèi", "thiết bị sản xuất", "生产设备必须保持良好状态。", "Shēngchǎn shèbèi bìxū bǎochí liánghǎo zhuàngtài.", "Thiết bị sản xuất phải luôn được giữ tốt.", "Danh từ"],
  ["保障", "bǎozhàng", "đảm bảo", "我们保障设备稳定运行。", "Wǒmen bǎozhàng shèbèi wěndìng yùnxíng.", "Chúng tôi đảm bảo thiết bị hoạt động ổn định.", "Động từ"],
  ["工作环境", "gōngzuò huánjìng", "môi trường làm việc", "公司创造安全健康的工作环境。", "Gōngsī chuàngzào ānquán jiànkāng de gōngzuò huánjìng.", "Công ty tạo môi trường làm việc an toàn và lành mạnh.", "Danh từ"],
  ["管理", "guǎnlǐ", "quản lý", "良好的管理有助于提高工作效率。", "Liánghǎo de guǎnlǐ yǒuzhùyú tígāo gōngzuò xiàolǜ.", "Quản lý tốt giúp nâng cao hiệu quả công việc.", "Động từ"]
    ],
  "hsk2": [
      ["入职", "rù zhí", "nhận việc", "今天是我正式入职的第一天。", "Jīntiān shì wǒ zhèngshì rùzhí de dì yī tiān.", "Hôm nay là ngày đầu tiên tôi chính thức nhận việc.", "Động từ"],
  ["团队", "tuán duì", "đội nhóm", "我很高兴能加入这个优秀的团队。", "Wǒ hěn gāoxìng néng jiārù zhège yōuxiù de tuánduì.", "Tôi rất vui khi được gia nhập đội nhóm xuất sắc này.", "Danh từ"],
  ["人事部", "rén shì bù", "phòng nhân sự", "我在公司的人事部工作。", "Wǒ zài gōngsī de rénshìbù gōngzuò.", "Tôi làm việc tại phòng nhân sự của công ty.", "Danh từ"],
  ["负责", "fù zé", "phụ trách", "他负责这个项目。", "Tā fùzé zhège xiàngmù.", "Anh ấy phụ trách dự án này.", "Động từ"],
  ["员工培训", "yuán gōng péi xùn", "đào tạo nhân viên", "我负责员工培训工作，员工培训对公司的发展很重要。", "Wǒ fùzé yuángōng péixùn gōngzuò, yuángōng péixùn duì gōngsī de fāzhǎn hěn zhòngyào.", "Tôi phụ trách công tác đào tạo nhân viên. Đào tạo nhân viên rất quan trọng đối với sự phát triển công ty.", "Danh từ"],
  ["入职培训", "rù zhí péi xùn", "đào tạo khi mới nhận việc", "公司会安排入职培训，培训内容直接关系到公司的组织架构和工作流程。", "Gōngsī huì ānpái rùzhí péixùn, péixùn nèiróng zhíjiē guānxì dào gōngsī de zǔzhī jiàgòu hé gōngzuò liúchéng.", "Công ty sẽ sắp xếp đào tạo đầu vào, nội dung đào tạo liên quan trực tiếp đến cơ cấu tổ chức công ty và lưu trình làm việc.", "Danh từ"],
  ["培训计划", "péi xùn jì huà", "kế hoạch đào tạo", "我们需要制定培训计划。", "Wǒmen xūyào zhìdìng péixùn jìhuà.", "Chúng ta cần xây dựng kế hoạch đào tạo.", "Danh từ"],
  ["培训资料", "péi xùn zī liào", "tài liệu đào tạo", "我正在整理培训资料。", "Wǒ zhèngzài zhěnglǐ péixùn zīliào.", "Tôi đang sắp xếp tài liệu đào tạo.", "Danh từ"],
  ["跟进", "gēn jìn", "theo dõi", "我会跟进培训效果。", "Wǒ huì gēnjìn péixùn xiàoguǒ.", "Tôi sẽ theo dõi hiệu quả đào tạo.", "Động từ"],
  ["评估", "píng gū", "đánh giá", "培训后需要进行评估。", "Péixùn hòu xūyào jìnxíng pínggū.", "Sau đào tạo cần tiến hành đánh giá.", "Động từ"],
  ["公司规章制度", "gōng sī guī zhāng zhì dù", "nội quy công ty", "新员工需要了解公司规章制度。", "Xīn yuángōng xūyào liǎojiě gōngsī guīzhāng zhìdù.", "Nhân viên mới cần hiểu nội quy công ty.", "Danh từ"],
  ["归属感", "guī shǔ gǎn", "cảm giác gắn bó", "培训可以增强员工的归属感。", "Péixùn kěyǐ zēngqiáng yuángōng de guīshǔgǎn.", "Đào tạo có thể gia tăng cảm giác gắn bó của nhân viên.", "Danh từ"],
  ["团队协作", "tuán duì xié zuò", "phối hợp đội nhóm", "团队协作可以提高工作效率。", "Tuánduì xiézuò kěyǐ tígāo gōngzuò xiàolǜ.", "Làm việc nhóm có thể nâng cao hiệu suất làm việc.", "Danh từ"],
  ["业务流程", "yè wù liú chéng", "quy trình nghiệp vụ", "我还在学习公司的业务流程。", "Wǒ hái zài xuéxí gōngsī de yèwù liúchéng.", "Tôi vẫn đang học quy trình công việc của công ty.", "Danh từ"],
  ["熟悉", "shú xī", "quen thuộc, nắm rõ", "我希望通过培训帮助新员工尽快熟悉公司环境。", "Wǒ xīwàng tōngguò péixùn bāngzhù xīn yuángōng jǐnkuài shúxī gōngsī huánjìng.", "Tôi hy vọng thông qua đào tạo giúp nhân viên mới nhanh chóng quen với môi trường công ty.", "Tính từ/Động từ"],
  ["整理", "zhěng lǐ", "sắp xếp, tổng hợp", "每天我都要整理培训资料。", "Měitiān wǒ dōu yào zhěnglǐ péixùn zīliào.", "Mỗi ngày tôi phải tổng hợp tài liệu đào tạo.", "Động từ"],
  ["协作", "xié zuò", "phối hợp", "团队协作在工作中很重要。", "Tuánduì xiézuò zài gōngzuò zhōng hěn zhòngyào.", "Sự phối hợp nhóm rất quan trọng trong công việc.", "Động từ"],
  ["责任感", "zé rèn gǎn", "tinh thần trách nhiệm", "公司希望员工有很强的责任感。", "Gōngsī xīwàng yuángōng yǒu hěn qiáng de zérèngǎn.", "Công ty mong nhân viên có tinh thần trách nhiệm cao.", "Danh từ"],
  ["提升", "tí shēng", "nâng cao (trình độ, năng lực)", "我会努力提升自己的能力。", "Wǒ huì nǔlì tíshēng zìjǐ de nénglì.", "Tôi sẽ cố gắng nâng cao năng lực của bản thân.", "Động từ"],
  ["逐步", "zhú bù", "từng bước", "我会逐步熟悉公司的业务流程。", "Wǒ huì zhúbù shúxī gōngsī de yèwù liúchéng.", "Tôi sẽ từng bước làm quen với quy trình công việc của công ty.", "Phó từ"],
  ["支持", "zhī chí", "hỗ trợ", "在工作中我们需要互相支持。", "Zài gōngzuò zhōng wǒmen xūyào hùxiāng zhīchí.", "Trong công việc chúng ta cần hỗ trợ lẫn nhau.", "Động từ/Danh từ"],
  ["贡献", "gòng xiàn", "đóng góp", "我希望能为公司的发展贡献一份力量。", "Wǒ xīwàng néng wèi gōngsī de fāzhǎn gòngxiàn yí fèn lìliàng.", "Tôi hy vọng đóng góp 1 phần sức lực cho sự phát triển của công ty.", "Động từ/Danh từ"],
  ["不辜负", "bù gū fù", "không phụ lòng", "我不会辜负公司的信任。", "Wǒ bú huì gūfù gōngsī de xìnrèn.", "Tôi sẽ không phụ sự tín nhiệm của công ty.", "Động từ"],
  ["投入", "tóu rù", "dồn vào, tập trung", "我会以积极的态度投入到工作中，把更多时间投入到员工培训中，作为新员工我会认真投入每一项工作，今后更加投入工作并不断提升自己。", "Wǒ huì yǐ jījí de tàidù tóurù dào gōngzuò zhōng, bǎ gèng duō shíjiān tóurù dào yuángōng péixùn zhōng, zuòwéi xīn yuángōng wǒ huì rènzhēn tóurù měi yí xiàng gōngzuò, jīn hòu gèngjiā tóurù gōngzuò bìng búduàn tíshēng zìjǐ.", "Tôi sẽ dùng thái độ tích cực để tập trung vào công việc, dành nhiều thời gian hơn cho công tác đào tạo nhân viên, là nhân viên mới tôi sẽ nghiêm túc dồn sức vào từng công việc, sau này sẽ càng tập trung vào công việc hơn và không ngừng nâng cao bản thân.", "Động từ"],
  ["诚挚", "chéng zhì", "Chân thành, trân trọng", "请允许我向各位领导和同事表示最诚挚的问候。", "Qǐng yǔnxǔ wǒ xiàng gèwèi lǐngdǎo hé tóngshì biǎoshì zuì chéngzhì de wènhòu.", "Xin cho phép tôi gửi lời chào trân trọng nhất đến các vị lãnh đạo và đồng nghiệp.", "Tính từ"],
  ["树立", "shù lì", "Xây dựng, thiết lập", "我们需要在客户面前树立良好的公司形象。", "Wǒmen xūyào zài kèhù miànqián shùlì liánghǎo de gōngsī xíngxiàng.", "Chúng ta cần phải xây dựng một hình ảnh công ty tốt đẹp trước mặt khách hàng.", "Động từ"],
  ["逐步", "zhú bù", "Từng bước, dần dần", "我们要逐步解决这些问题。", "Wǒmen yào zhúbù jiějué zhèxiē wèntí.", "Chúng ta cần từng bước giải quyết những vấn đề này.", "Phó từ"],
  ["给予", "jǐ yǔ", "Dành cho, ban cho", "感谢公司给予我这个机会。", "Gǎnxiè gōngsī jǐyǔ wǒ zhège jīhuì.", "Cảm ơn công ty đã dành cho tôi cơ hội này.", "Động từ"]
  ],
  "hsk3": [
   ["董事长", "dǒng shì zhǎng", "Chủ tịch Hội đồng quản trị", "董事长正在开会。", "Dǒngshìzhǎng zhèngzài kāihuì.", "Chủ tịch hội đồng quản trị đang họp.", "Danh từ"],
  ["副董事长", "fù dǒng shì zhǎng", "Phó Chủ tịch HĐQT", "副董事长明天去出差。", "Fù dǒngshìzhǎng míngtiān qù chūchāi.", "Phó chủ tịch HĐQT ngày mai đi công tác.", "Danh từ"],
  ["总经理", "zǒng jīng lǐ", "Tổng Giám đốc", "总经理批准了这个项目。", "Zǒngjīnglǐ pīzhǔn le zhège xiàngmù.", "Tổng giám đốc đã phê duyệt dự án này.", "Danh từ"],
  ["副总经理", "fù zǒng jīng lǐ", "Phó Tổng Giám đốc", "副总经理负责公司的日常运营。", "Fù zǒngjīnglǐ fùzé gōngsī de rìcháng yùnyíng.", "Phó tổng giám đốc phụ trách vận hành hàng ngày của công ty.", "Danh từ"],
  ["总监", "zǒng jiān", "Giám đốc khối", "他是我们公司的财务总监。", "Tā shì wǒmen gōngsī de cáiwù zǒngjiān.", "Ông ấy là giám đốc khối tài chính của công ty chúng tôi.", "Danh từ"],
  ["部门经理", "bù mén jīng lǐ", "Trưởng phòng", "请把这份文件交给部门经理。", "Qǐng bǎ zhè fèn wénjiàn jiāo gěi bùmén jīnglǐ.", "Vui lòng giao tài liệu này cho trưởng phòng.", "Danh từ"],
  ["副经理", "fù jīng lǐ", "Phó Trưởng phòng", "副经理正在安排工作。", "Fù jīnglǐ zhèngzài ānpái gōngzuò.", "Phó trưởng phòng đang sắp xếp công việc.", "Danh từ"],
  ["主管", "zhǔ guǎn", "Chủ quản / Quản lý bộ phận", "他刚刚升任销售主管。", "Tā gānggāng shēngrèn xiāoshòu zhǔguǎn.", "Anh ấy vừa được thăng chức thành quản lý bộ phận bán hàng.", "Danh từ"],
  ["科长", "kē zhǎng", "Trưởng nhóm/Trưởng tổ", "科长对大家的工作很满意。", "Kēzhǎng duì dàjiā de gōngzuò hěn mǎnyì.", "Trưởng nhóm rất hài lòng với công việc của mọi người.", "Danh từ"],
  ["班长", "bān zhǎng", "Tổ trưởng sản xuất", "班长在检查生产线。", "Bānzhǎng zài jiǎnchá shēngchǎnxiàn.", "Tổ trưởng sản xuất đang kiểm tra dây chuyền sản xuất.", "Danh từ"],
  ["工程师", "gōng chéng shī", "Kỹ sư", "他是一名软件工程师。", "Tā shì yì míng ruǎnjiàn gōngchéngshī.", "Anh ấy là một kỹ sư phần mềm.", "Danh từ"],
  ["技术员", "jì shù yuán", "Nhân viên kỹ thuật", "技术员正在维修设备。", "Jìshùyuán zhèngzài wéixiū shèbèi.", "Nhân viên kỹ thuật đang sửa chữa thiết bị.", "Danh từ"],
  ["专员", "zhuān yuán", "Chuyên viên", "我是人力资源专员。", "Wǒ shì rénlì zīyuán zhuānyuán.", "Tôi là chuyên viên nhân sự.", "Danh từ"],
  ["助理", "zhù lǐ", "Trợ lý", "经理助理帮你安排会议。", "Jīnglǐ zhùlǐ bāng nǐ ānpái huìyì.", "Trợ lý giám đốc giúp bạn sắp xếp cuộc họp.", "Danh từ"],
  ["员工", "yuán gōng", "Nhân viên", "公司有两百多名员工。", "Gōngsī yǒu liǎng bǎi duō míng yuángōng.", "Công ty có hơn hai trăm nhân viên.", "Danh từ"],
  ["实习生", "shí xí shēng", "Thực tập sinh", "公司今年招了十个实习生。", "Gōngsī jīnnián zhāo le shí gè shíxíshēng.", "Công ty năm nay tuyển mười thực tập sinh.", "Danh từ"],
  ["高层管理", "gāo céng guǎn lǐ", "Quản lý cấp cao", "高层管理需要具备战略眼光。", "Gāocéng guǎnlǐ xūyào jùbèi zhànlüè yǎnguāng.", "Quản lý cấp cao cần có tầm nhìn chiến lược.", "Danh từ"],
  ["中层管理", "zhōng céng guǎn lǐ", "Quản lý cấp trung", "中层管理是公司的中坚力量。", "Zhōngcéng guǎnlǐ shì gōngsī de zhōngjiān lìliàng.", "Quản lý cấp trung là lực lượng nòng cốt của công ty.", "Danh từ"],
  ["基层管理", "jī céng guǎn lǐ", "Quản lý cấp cơ sở", "基层管理直接接触生产一线。", "Jīcéng guǎnlǐ zhíjiē jiēchù shēngchǎn yíxiàn.", "Quản lý cấp cơ sở trực tiếp tiếp xúc với dây chuyền sản xuất.", "Danh từ"],
  ["管理层", "guǎn lǐ céng", "Cấp quản lý", "管理层做出了新的决定。", "Guǎnlǐcéng zuòchū le xīn de juédìng.", "Cấp quản lý đã đưa ra quyết định mới.", "Danh từ"],
  ["非管理岗位", "fēi guǎn lǐ gǎng wèi", "Vị trí không quản lý", "非管理岗位也同样重要。", "Fēi guǎnlǐ gǎngwèi yě tóngyàng zhòngyào.", "Vị trí không quản lý cũng quan trọng không kém.", "Danh từ"],
  ["管理岗", "guǎn lǐ gǎng", "Vị trí quản lý", "他申请了一个管理岗。", "Tā shēnqǐng le yí gè guǎnlǐ gǎng.", "Anh ấy đã ứng tuyển vào một vị trí quản lý.", "Danh từ"],
  ["专业技术岗", "zhuān yè jì shù gǎng", "Vị trí kỹ thuật/chuyên môn", "这个部门主要是专业技术岗。", "Zhège bùmén zhǔyào shì zhuānyè jìshù gǎng.", "Bộ phận này chủ yếu là vị trí kỹ thuật/chuyên môn.", "Danh từ"],
  ["操作岗", "cāo zuò gǎng", "Vị trí vận hành", "操作岗需要经过严格培训。", "Cāozuò gǎng xūyào jīngguò yángé péixùn.", "Vị trí vận hành cần trải qua đào tạo nghiêm ngặt.", "Danh từ"],
  ["晋升", "jìn shēng", "Thăng chức", "他因为工作出色获得了晋升。", "Tā yīnwèi gōngzuò chūsè huòdé le jìnshēng.", "Anh ấy được thăng chức vì làm việc xuất sắc.", "Động từ"],
  ["降职", "jiàng zhí", "Giáng chức", "由于失误，他被降职了。", "Yóuyú shīwù, tā bèi jiàngzhí le.", "Do sai sót, anh ấy đã bị giáng chức.", "Động từ"]
],
  "hsk4": [
    ["提", "tí", "nhắc đến, xách", "别提这件事了。", "Bié tí zhè jiàn shì le.", "Đừng nhắc đến chuyện này nữa.", "Động từ"],
    ["以为", "yǐwéi", "tưởng rằng, cho rằng (thường sai lệch với thực tế)", "我以为你已经走了。", "Wǒ yǐwéi nǐ yǐjīng zǒu le.", "Tôi tưởng rằng bạn đã đi rồi.", "Động từ"],
    ["份", "fèn", "phần, bản (lượng từ công việc, báo...)", "他找到了一份好工作。", "Tā zhǎodào le yí fèn hǎo gōngzuò.", "Anh ấy đã tìm được một công việc tốt.", "Lượng từ"],
    ["完全", "wánquán", "hoàn toàn", "我完全同意你的看法。", "Wǒ wánquán tóngyì nǐ de kànfǎ.", "Tôi hoàn toàn đồng ý với cách nhìn của bạn.", "Phó từ/Tính từ"],
    ["赚", "zhuàn", "kiếm tiền", "他做生意赚了很多钱。", "Tā zuò shēngyi zhuàn le hěn duō qián.", "Anh ấy làm ăn kiếm được rất nhiều tiền.", "Động từ"],
    ["调查", "diàochá", "điều tra, khảo sát", "警方正在调查这个案子。", "Jǐngfāng zhèngzài diàochá zhège ànzi.", "Cảnh sát đang điều tra vụ án này.", "Động từ/Danh từ"],
    ["原来", "yuánlái", "hóa ra, vốn dĩ", "原来是你啊！", "Yuánlái shì nǐ a!", "Hóa ra là bạn à!", "Phó từ/Tính từ"],
    ["计划", "jìhuà", "kế hoạch", "明年的计划你做好了吗？", "Míngnián de jìhuà nǐ zuò hǎo le ma?", "Kế hoạch năm sau bạn đã làm xong chưa?", "Danh từ/Động từ"],
    ["提前", "tíqián", "làm trước, sớm hơn", "会议提前结束了。", "Huìyì tíqián jiéshù le.", "Cuộc họp đã kết thúc sớm hơn.", "Động từ"],
    ["保证", "bǎozhèng", "đảm bảo, bảo đảm", "我保证明天一定到。", "Wǒ bǎozhèng míngtiān yídìng dào.", "Tôi đảm bảo ngày mai nhất định đến.", "Động từ"],
    ["提醒", "tíxǐng", "nhắc nhở", "谢谢你提醒我。", "Xièxie nǐ tíxǐng wǒ.", "Cảm ơn bạn đã nhắc nhở tôi.", "Động từ"],
    ["乱", "luàn", "lộn xộn, bừa bãi", "房间里太乱了，快整理一下。", "Fángjiān lǐ tài luàn le, kuài zhěnglǐ yíxià.", "Trong phòng bừa bãi quá, mau dọn dẹp đi.", "Tính từ"],
    ["生意", "shēngyi", "việc làm ăn, buôn bán", "他家的生意做得很大。", "Tā jiā de shēngyi zuò de hěn dà.", "Việc làm ăn của nhà anh ấy rất lớn.", "Danh từ"],
    ["谈", "tán", "nói chuyện, bàn bạc", "我们来谈谈合作的事吧。", "Wǒmen lái tán tan hézuò de shì ba.", "Chúng ta hãy bàn bạc về chuyện hợp tác nhé.", "Động từ"],
    ["并", "bìng", "không hề (nhấn mạnh phủ định)", "我并不认识他。", "Wǒ bìng bú rènshi tā.", "Tôi hoàn toàn không quen anh ta.", "Phó từ"],
    ["积累", "jīlěi", "tích lũy", "工作经验需要慢慢积累。", "Gōngzuò jīngyàn xūyào mànman jīlěi.", "Kinh nghiệm làm việc cần được tích lũy từ từ.", "Động từ"],
    ["经验", "jīngyàn", "kinh nghiệm", "他有丰富的工作经验。", "Tā yǒu fēngfù de gōngzuò jīngyàn.", "Anh ấy có kinh nghiệm làm việc phong phú.", "Danh từ"],
    ["一切", "yíqiè", "tất cả, mọi thứ", "一切都会好起来的。", "Yíqiè dōu huì hǎo qǐlái de.", "Mọi thứ rồi sẽ tốt lên thôi.", "Đại từ"],
    ["按照", "ànzhào", "dựa theo, theo như", "请按照说明书使用。", "Qǐng ànzhào shuōmíngshū shǐyòng.", "Xin hãy sử dụng theo như sách hướng dẫn.", "Giới từ"],
    ["成功", "chénggōng", "thành công", "只要努力，就会成功。", "Zhǐyào nǔlì, jiù huì chénggōng.", "Chỉ cần nỗ lực thì sẽ thành công.", "Động từ/Tính từ/Danh từ"],
    ["顺利", "shùnlì", "thuận lợi", "祝你工作顺利！", "Zhù nǐ gōngzuò shùnlì!", "Chúc bạn công việc thuận lợi!", "Tính từ"],
    ["感谢", "gǎnxiè", "cảm ơn", "非常感谢您的帮助。", "Fēicháng gǎnxiè nín de bāngzhù.", "Vô cùng cảm ơn sự giúp đỡ của ngài.", "Động từ"],
    ["消息", "xiāoxi", "tin tức", "这是一个好消息。", "Zhè shì yí ge hǎo xiāoxi.", "Đây là một tin tức tốt.", "Danh từ"],
    ["按时", "ànshí", "đúng giờ, đúng hạn", "你要按时吃药。", "Nǐ yào ànshí chī yào.", "Bạn phải uống thuốc đúng giờ.", "Phó từ"],
    ["奖金", "jiǎngjīn", "tiền thưởng", "年底公司发了奖金。", "Niándǐ gōngsī fā le jiǎngjīn.", "Cuối năm công ty đã phát tiền thưởng.", "Danh từ"],
    ["工资", "gōngzī", "tiền lương", "这份工作的工资很高。", "Zhè fèn gōngzuò de gōngzī hěn gāo.", "Tiền lương của công việc này rất cao.", "Danh từ"],
    ["方法", "fāngfǎ", "phương pháp", "这种学习方法很有效。", "Zhè zhǒng xuéxí fāngfǎ hěn yǒuxiào.", "Phương pháp học tập này rất hiệu quả.", "Danh từ"],
    ["知识", "zhīshi", "kiến thức", "书本里有很多知识。", "Shūběn lǐ yǒu hěn duō zhīshi.", "Trong sách có rất nhiều kiến thức.", "Danh từ"],
    ["不得不", "bù dé bù", "không thể không", "下大雨了，我不得不待在家里。", "Xià dàyǔ le, wǒ bù dé bù dāi zài jiālǐ.", "Trời mưa to rồi, tôi không thể không ở nhà.", "Phó từ"],
    ["甚至", "shènzhì", "thậm chí", "他太忙了，甚至连吃饭的时间都没有。", "Tā tài máng le, shènzhì lián chīfàn de shíjiān dōu méiyǒu.", "Anh ấy bận quá, thậm chí thời gian ăn cơm cũng không có.", "Phó từ"],
    ["责任", "zérèn", "trách nhiệm", "这是我的责任。", "Zhè shì wǒ de zérèn.", "Đây là trách nhiệm của tôi.", "Danh từ"]
  ],
  "hsk5": [
    ["家具", "jiājù", "đồ nội thất", "我想买一些新家具。", "Wǒ xiǎng mǎi yìxiē xīn jiājù.", "Tôi muốn mua một ít đồ nội thất mới.", "Danh từ"],
    ["沙发", "shāfā", "ghế sofa", "这个沙发很舒服。", "Zhège shāfā hěn shūfu.", "Chiếc sofa này rất thoải mái.", "Danh từ"],
    ["打折", "dǎzhé", "giảm giá", "这家商店在打折。", "Zhè jiā shāngdiàn zài dǎzhé.", "Cửa hàng này đang giảm giá.", "Động từ"],
    ["价格", "jiàgé", "giá cả", "它的价格比较便宜。", "Tā de jiàgé bǐjiào piányi.", "Giá của nó tương đối rẻ.", "Danh từ"],
    ["质量", "zhìliàng", "chất lượng", "这件衣服的质量很好。", "Zhè jiàn yīfu de zhìliàng hěn hǎo.", "Chất lượng của bộ quần áo này rất tốt.", "Danh từ"],
    ["肯定", "kěndìng", "chắc chắn", "他肯定会来的。", "Tā kěndìng huì lái de.", "Anh ấy chắc chắn sẽ đến.", "Phó từ"],
    ["流行", "liúxíng", "thịnh hành, phổ biến", "这首歌现在很流行。", "Zhè shǒu gē xiànzài hěn liúxíng.", "Bài hát này bây giờ rất thịnh hành.", "Tính từ/Động từ"],
    ["顺便", "shùnbiàn", "tiện thể", "你下班顺便买点儿水果吧。", "Nǐ xiàbān shùnbiàn mǎi diǎnr shuǐguǒ ba.", "Bạn tan làm tiện thể mua ít trái cây nhé.", "Phó từ"],
    ["台", "tái", "chiếc, đài (lượng từ dùng cho máy móc)", "我买了一台新电视。", "Wǒ mǎi le yì tái xīn diànshì.", "Tôi mua một chiếc tivi mới.", "Lượng từ"],
    ["光", "guāng", "chỉ, hết sạch", "钱都花光了。", "Qián dōu huā guāng le.", "Tiền tiêu hết sạch rồi.", "Phó từ/Tính từ"],
    ["实在", "shízài", "thực sự, chân thật", "他是一个很实在的人。", "Tā shì yí ge hěn shízài de rén.", "Anh ấy là một người rất chân thật.", "Phó từ/Tính từ"],
    ["制冷", "zhìlěng", "làm lạnh", "这个空调制冷效果很好。", "Zhège kōngtiáo zhìlěng xiàoguǒ hěn hǎo.", "Hiệu quả làm lạnh của chiếc điều hòa này rất tốt.", "Động từ"],
    ["效果", "xiàoguǒ", "hiệu quả", "这种药的效果不错。", "Zhè zhǒng yào de xiàoguǒ búcuò.", "Hiệu quả của loại thuốc này không tồi.", "Danh từ"],
    ["现金", "xiànjīn", "tiền mặt", "我身上没带现金。", "Wǒ shēnshang méi dài xiànjīn.", "Trên người tôi không mang theo tiền mặt.", "Danh từ"],
    ["邀请", "yāoqǐng", "mời", "感谢你的邀请。", "Gǎnxiè nǐ de yāoqǐng.", "Cảm ơn lời mời của bạn.", "Động từ/Danh từ"],
    ["葡萄", "pútao", "nho", "这些葡萄很甜。", "Zhèxiē pútao hěn tián.", "Những quả nho này rất ngọt.", "Danh từ"],
    ["艺术", "yìshù", "nghệ thuật", "他对艺术很感兴趣。", "Tā duì yìshù hěn gǎn xìngqù.", "Anh ấy rất có hứng thú với nghệ thuật.", "Danh từ"],
    ["广告", "guǎnggào", "quảng cáo", "我看到了一则广告。", "Wǒ kàndào le yì zé guǎnggào.", "Tôi đã nhìn thấy một mẩu quảng cáo.", "Danh từ"],
    ["味道", "wèidào", "mùi vị", "这个菜的味道真好。", "Zhège cài de wèidào zhēn hǎo.", "Mùi vị của món này thật ngon.", "Danh từ"],
    ["实际", "shíjì", "thực tế", "要结合实际情况来考虑。", "Yào jiéhé shíjì qíngkuàng lái kǎolǜ.", "Phải kết hợp tình hình thực tế để xem xét.", "Danh từ/Tính từ"],
    ["考虑", "kǎolǜ", "xem xét, suy nghĩ", "我会认真考虑你的建议。", "Wǒ huì rènzhēn kǎolǜ nǐ de jiànyì.", "Tôi sẽ nghiêm túc xem xét đề nghị của bạn.", "Động từ"],
    ["标准", "biāozhǔn", "tiêu chuẩn", "这符合我们的标准。", "Zhè fúhé wǒmen de biāozhǔn.", "Điều này phù hợp với tiêu chuẩn của chúng tôi.", "Danh từ"],
    ["样子", "yàngzi", "dáng vẻ, hình dáng", "这件衣服的样子很特别。", "Zhè jiàn yīfu de yàngzi hěn tèbié.", "Hình dáng của bộ quần áo này rất đặc biệt.", "Danh từ"],
    ["年龄", "niánlíng", "tuổi tác", "您的年龄是多少？", "Nín de niánlíng shì duōshao?", "Tuổi tác của ngài là bao nhiêu?", "Danh từ"],
    ["浪费", "làngfèi", "lãng phí", "不要浪费时间了。", "Búyào làngfèi shíjiān le.", "Đừng lãng phí thời gian nữa.", "Động từ"],
    ["购物", "gòuwù", "mua sắm", "周末我们去购物中心吧。", "Zhōumò wǒmen qù gòuwù zhōngxīn ba.", "Cuối tuần chúng ta đi trung tâm mua sắm nhé.", "Động từ"],
    ["尤其", "yóuqí", "đặc biệt là", "他喜欢运动，尤其是打篮球。", "Tā xǐhuan yùndòng, yóuqí shì dǎ lánqiú.", "Anh ấy thích thể thao, đặc biệt là chơi bóng rổ.", "Phó từ"],
    ["受到", "shòudào", "nhận được, bị", "他受到了大家的表扬。", "Tā shòudào le dàjiā de biǎoyáng.", "Anh ấy đã nhận được sự tuyên dương của mọi người.", "Động từ"],
    ["任何", "rènhé", "bất kỳ", "如果有任何问题，请告诉我。", "Rúguǒ yǒu rènhé wèntí, qǐng gàosu wǒ.", "Nếu có bất kỳ vấn đề gì, xin hãy nói cho tôi biết.", "Đại từ"],
    ["寄", "jì", "gửi (thư, bưu kiện)", "我去邮局寄包裹。", "Wǒ qù yóujú jì bāoguǒ.", "Tôi đi bưu điện gửi bưu kiện.", "Động từ"]
  ],
  "hsk6": [
    ["售货员", "shòuhuòyuán", "nhân viên bán hàng", "她是一名售货员。", "Tā shì yì míng shòuhuòyuán.", "Cô ấy là một nhân viên bán hàng.", "Danh từ"],
    ["袜子", "wàzi", "tất, vớ", "这双袜子很舒服。", "Zhè shuāng wàzi hěn shūfu.", "Đôi tất này rất thoải mái.", "Danh từ"],
    ["打扰", "dǎrǎo", "làm phiền", "对不起，打扰一下。", "Duìbùqǐ, dǎrǎo yíxià.", "Xin lỗi, làm phiền một chút.", "Động từ"],
    ["竟然", "jìngrán", "lại, vậy mà", "他竟然没来。", "Tā jìngrán méi lái.", "Anh ấy vậy mà lại không đến.", "Phó từ"],
    ["西红柿", "xīhóngshì", "cà chua", "我喜欢吃西红柿。", "Wǒ xǐhuan chī xīhóngshì.", "Tôi thích ăn cà chua.", "Danh từ"],
    ["百分之", "bǎifēnzhī", "phần trăm", "百分之八十的人同意了。", "Bǎifēnzhī bāshí de rén tóngyì le.", "80 phần trăm người đã đồng ý.", "Cụm từ"],
    ["倍", "bèi", "lần, gấp bội", "他的工资是我的两倍。", "Tā de gōngzī shì wǒ de liǎng bèi.", "Lương của anh ấy gấp đôi của tôi.", "Lượng từ"],
    ["皮肤", "pífū", "da", "她的皮肤很好。", "Tā de pífū hěn hǎo.", "Da của cô ấy rất đẹp.", "Danh từ"],
    ["好处", "hǎochù", "điểm tốt, lợi ích", "运动对身体有好处。", "Yùndòng duì shēntǐ yǒu hǎochù.", "Vận động có lợi cho cơ thể.", "Danh từ"],
    ["尝", "cháng", "nếm", "你尝尝这个菜。", "Nǐ cháng chang zhège cài.", "Bạn nếm thử món này xem.", "Động từ"],
    ["轻", "qīng", "nhẹ", "这个箱子很轻。", "Zhège xiāngzi hěn qīng.", "Cái rương này rất nhẹ.", "Tính từ"],
    ["方面", "fāngmiàn", "phương diện, mặt", "在这个方面他很有经验。", "Zài zhège fāngmiàn tā hěn yǒu jīngyàn.", "Về mặt này anh ấy rất có kinh nghiệm.", "Danh từ"],
    ["值得", "zhídé", "đáng, xứng đáng", "这本书值得一读。", "Zhè běn shū zhídé yì dú.", "Cuốn sách này đáng để đọc một lần.", "Động từ"],
    ["活动", "huódòng", "hoạt động", "周末你有什么活动？", "Zhōumò nǐ yǒu shénme huódòng?", "Cuối tuần bạn có hoạt động gì?", "Danh từ/Động từ"],
    ["内", "nèi", "trong", "请在三天内完成。", "Qǐng zài sān tiān nèi wánchéng.", "Xin hãy hoàn thành trong vòng ba ngày.", "Danh từ"],
    ["免费", "miǎnfèi", "miễn phí", "这里提供免费早餐。", "Zhèlǐ tígōng miǎnfèi zǎocān.", "Ở đây cung cấp bữa sáng miễn phí.", "Động từ"],
    ["修理", "xiūlǐ", "sửa chữa", "我的自行车需要修理。", "Wǒ de zìxíngchē xūyào xiūlǐ.", "Xe đạp của tôi cần phải sửa chữa.", "Động từ"],
    ["支持", "zhīchí", "ủng hộ", "感谢大家的支持。", "Gǎnxiè dàjiā de zhīchí.", "Cảm ơn sự ủng hộ của mọi người.", "Động từ/Danh từ"],
    ["举行", "jǔxíng", "tổ chức", "会议将在明天举行。", "Huìyì jiāng zài míngtiān jǔxíng.", "Cuộc họp sẽ được tổ chức vào ngày mai.", "Động từ"],
    ["满", "mǎn", "đầy, đủ", "水倒满了。", "Shuǐ dào mǎn le.", "Nước rót đầy rồi.", "Tính từ"],
    ["其中", "qízhōng", "trong đó", "我们班有三十人，其中一半是女生。", "Wǒmen bān yǒu sānshí rén, qízhōng yíbàn shì nǚshēng.", "Lớp chúng tôi có 30 người, trong đó một nửa là nữ.", "Đại từ"],
    ["小说", "xiǎoshuō", "tiểu thuyết", "他喜欢看小说。", "Tā xǐhuan kàn xiǎoshuō.", "Anh ấy thích đọc tiểu thuyết.", "Danh từ"],
    ["会员卡", "huìyuánkǎ", "thẻ hội viên", "你有这家店的会员卡吗？", "Nǐ yǒu zhè jiā diàn de huìyuánkǎ ma?", "Bạn có thẻ hội viên của cửa hàng này không?", "Danh từ"],
    ["所有", "suǒyǒu", "tất cả", "这里所有的书都是我的。", "Zhèlǐ suǒyǒu de shū dōu shì wǒ de.", "Tất cả sách ở đây đều là của tôi.", "Tính từ"],
    ["获得", "huòdé", "giành được, đạt được", "他获得了第一名。", "Tā huòdé le dì yī míng.", "Anh ấy đã giành được giải nhất.", "Động từ"],
    ["情况", "qíngkuàng", "tình hình", "现在的情况很复杂。", "Xiànzài de qíngkuàng hěn fùzá.", "Tình hình bây giờ rất phức tạp.", "Danh từ"],
    ["例如", "lìrú", "ví dụ", "很多水果都很甜，例如苹果、西瓜。", "Hěn duō shuǐguǒ dōu hěn tián, lìrú píngguǒ, xīguā.", "Rất nhiều trái cây rất ngọt, ví dụ như táo, dưa hấu.", "Động từ"],
    ["举办", "jǔbàn", "tổ chức", "学校举办了一次运动会。", "Xuéxiào jǔbàn le yí cì yùndònghuì.", "Trường học đã tổ chức một hội thao.", "Động từ"],
    ["各", "gè", "các, mỗi", "各位旅客请注意。", "Gèwèi lǚkè qǐng zhùyì.", "Xin quý hành khách chú ý.", "Đại từ"],
    ["降低", "jiàngdī", "hạ thấp, giảm", "这里的温度降低了。", "Zhèlǐ de wēndù jiàngdī le.", "Nhiệt độ ở đây đã giảm xuống.", "Động từ"]
  ],
  "hsk7": [
    ["流血", "liú xiě", "chảy máu", "你的手流血了。", "Nǐ de shǒu liú xiě le.", "Tay của bạn chảy máu rồi.", "Động từ"],
    ["擦", "cā", "lau, chùi", "请用纸巾擦一下。", "Qǐng yòng zhǐjīn cā yíxià.", "Vui lòng dùng khăn giấy lau một chút.", "Động từ"],
    ["气候", "qìhòu", "khí hậu", "这里的气候很适合居住。", "Zhèlǐ de qìhòu hěn shìhé jūzhù.", "Khí hậu ở đây rất thích hợp để ở.", "Danh từ"],
    ["估计", "gūjì", "ước lượng, đoán", "我估计他今天不会来了。", "Wǒ gūjì tā jīntiān bú huì lái le.", "Tôi đoán hôm nay anh ấy sẽ không đến.", "Động từ"],
    ["咳嗽", "késou", "ho", "他感冒了，一直咳嗽。", "Tā gǎnmào le, yìzhí késou.", "Anh ấy bị cảm, ho suốt.", "Động từ"],
    ["严重", "yánzhòng", "nghiêm trọng", "他的病很严重。", "Tā de bìng hěn yánzhòng.", "Bệnh của anh ấy rất nghiêm trọng.", "Tính từ"],
    ["窗户", "chuānghu", "cửa sổ", "请把窗户打开。", "Qǐng bǎ chuānghu dǎkāi.", "Vui lòng mở cửa sổ ra.", "Danh từ"],
    ["空气", "kōngqì", "không khí", "早上的空气很新鲜。", "Zǎoshang de kōngqì hěn xīnxiān.", "Không khí buổi sáng rất trong lành.", "Danh từ"],
    ["抽烟", "chōuyān", "hút thuốc", "请不要在这里抽烟。", "Qǐng búyào zài zhèlǐ chōuyān.", "Xin đừng hút thuốc ở đây.", "Động từ"],
    ["动作", "dòngzuò", "động tác", "这个动作很难做。", "Zhège dòngzuò hěn nán zuò.", "Động tác này rất khó làm.", "Danh từ"],
    ["帅", "shuài", "đẹp trai", "他长得很帅。", "Tā zhǎng de hěn shuài.", "Anh ấy trông rất đẹp trai.", "Tính từ"],
    ["出现", "chūxiàn", "xuất hiện", "天上出现了一道彩虹。", "Tiān shàng chūxiàn le yí dào cǎihóng.", "Trên trời xuất hiện một đạo cầu vồng.", "Động từ"],
    ["后悔", "hòuhuǐ", "hối hận", "我后悔没听你的话。", "Wǒ hòuhuǐ méi tīng nǐ de huà.", "Tôi hối hận vì đã không nghe lời bạn.", "Động từ"],
    ["来不及", "láibují", "không kịp", "快点，不然就来不及了。", "Kuài diǎn, bùrán jiù láibují le.", "Nhanh lên, nếu không thì không kịp đâu.", "Động từ"],
    ["反对", "fǎnduì", "phản đối", "我们都反对这个计划。", "Wǒmen dōu fǎnduì zhège jìhuà.", "Chúng tôi đều phản đối kế hoạch này.", "Động từ"],
    ["大夫", "dàifu", "bác sĩ", "大夫说我需要休息。", "Dàifu shuō wǒ xūyào xiūxi.", "Bác sĩ nói tôi cần nghỉ ngơi.", "Danh từ"],
    ["植物", "zhíwù", "thực vật", "院子里种了很多植物。", "Yuànzi lǐ zhòng le hěn duō zhíwù.", "Trong sân trồng rất nhiều thực vật.", "Danh từ"],
    ["研究", "yánjiū", "nghiên cứu", "他在研究中国历史。", "Tā zài yánjiū Zhōngguó lìshǐ.", "Anh ấy đang nghiên cứu lịch sử Trung Quốc.", "Động từ/Danh từ"],
    ["超过", "chāoguò", "vượt qua", "他的成绩超过了我。", "Tā de chéngjì chāoguò le wǒ.", "Thành tích của cậu ấy đã vượt qua tôi.", "Động từ"],
    ["散步", "sànbù", "đi dạo", "吃完饭我们去散步吧。", "Chī wán fàn wǒmen qù sànbù ba.", "Ăn xong chúng ta đi dạo nhé.", "Động từ"],
    ["指", "zhǐ", "chỉ, trỏ", "他指着前面的大楼。", "Tā zhǐ zhe qiánmiàn de dàlóu.", "Anh ấy chỉ vào tòa nhà phía trước.", "Động từ"],
    ["精神", "jīngshén", "tinh thần", "他的精神状态很好。", "Tā de jīngshén zhuàngtài hěn hǎo.", "Trạng thái tinh thần của anh ấy rất tốt.", "Danh từ"],
    ["教授", "jiàoshòu", "giáo sư", "王教授是我的老师。", "Wáng jiàoshòu shì wǒ de lǎoshī.", "Giáo sư Vương là thầy của tôi.", "Danh từ"],
    ["数字", "shùzì", "con số", "请写下这些数字。", "Qǐng xiě xià zhèxiē shùzì.", "Xin hãy viết xuống những con số này.", "Danh từ"],
    ["说明", "shuōmíng", "giải thích, thuyết minh", "请说明一下你的理由。", "Qǐng shuōmíng yíxià nǐ de lǐyóu.", "Xin hãy giải thích một chút lý do của bạn.", "Động từ/Danh từ"],
    ["要是", "yàoshì", "nếu như", "要是明天下雨，我们就不去了。", "Yàoshì míngtiān xiàyǔ, wǒmen jiù bú qù le.", "Nếu như ngày mai mưa, chúng ta sẽ không đi nữa.", "Liên từ"],
    ["既", "jì", "đã, vừa", "这件衣服既便宜又好看。", "Zhè jiàn yīfu jì piányi yòu hǎokàn.", "Bộ quần áo này vừa rẻ lại vừa đẹp.", "Liên từ"],
    ["减肥", "jiǎnféi", "giảm béo", "她正在努力减肥。", "Tā zhèngzài nǔlì jiǎnféi.", "Cô ấy đang nỗ lực giảm béo.", "Động từ"],
    ["辛苦", "xīnkǔ", "vất vả", "大家工作都挺辛苦的。", "Dàjiā gōngzuò dōu tǐng xīnkǔ de.", "Mọi người làm việc đều khá vất vả.", "Tính từ"],
    ["肚子", "dùzi", "bụng", "我肚子疼。", "Wǒ dùzi téng.", "Tôi đau bụng.", "Danh từ"],
    ["感情", "gǎnqíng", "tình cảm", "他们俩感情很好。", "Tāmen liǎ gǎnqíng hěn hǎo.", "Tình cảm của hai người họ rất tốt.", "Danh từ"],
    ["烦恼", "fánnǎo", "phiền não", "别为这件事烦恼了。", "Bié wèi zhè jiàn shì fánnǎo le.", "Đừng phiền não vì chuyện này nữa.", "Tính từ/Danh từ"],
    ["掉", "diào", "rơi, rớt", "我的钥匙掉在地上。", "Wǒ de yàoshi diào zài dìshàng.", "Chìa khóa của tôi rớt trên mặt đất.", "Động từ"]
],
  "hsk8": [
    ["巧克力", "qiǎokèlì", "sô-cô-la", "她送给我一盒巧克力。", "Tā sòng gěi wǒ yì hé qiǎokèlì.", "Cô ấy tặng tôi một hộp sô-cô-la.", "Danh từ"],
    ["亲戚", "qīnqi", "họ hàng", "春节时我们会去走亲戚。", "Chūnjié shí wǒmen huì qù zǒu qīnqi.", "Lúc Tết chúng tôi sẽ đi thăm họ hàng.", "Danh từ"],
    ["伤心", "shāngxīn", "đau lòng, buồn bã", "听到这个消息，我很伤心。", "Tīngdào zhège xiāoxi, wǒ hěn shāngxīn.", "Nghe được tin này, tôi rất buồn.", "Tính từ"],
    ["使", "shǐ", "khiến cho, làm cho", "这件事使他非常生气。", "Zhè jiàn shì shǐ tā fēicháng shēngqì.", "Chuyện này khiến anh ấy vô cùng tức giận.", "Động từ"],
    ["心疼", "xīnténg", "thương, xót xa", "看到她生病，我很心疼。", "Kàndào tā shēngbìng, wǒ hěn xīnténg.", "Thấy cô ấy ốm, tôi rất xót xa.", "Động từ"],
    ["心情", "xīnqíng", "tâm trạng", "我今天心情很好。", "Wǒ jīntiān xīnqíng hěn hǎo.", "Tâm trạng tôi hôm nay rất tốt.", "Danh từ"],
    ["愉快", "yúkuài", "vui vẻ", "祝你周末愉快！", "Zhù nǐ zhōumò yúkuài!", "Chúc bạn cuối tuần vui vẻ!", "Tính từ"],
    ["景色", "jǐngsè", "phong cảnh, cảnh sắc", "这里的景色真美。", "Zhèlǐ de jǐngsè zhēn měi.", "Phong cảnh ở đây thật đẹp.", "Danh từ"],
    ["放松", "fàngsōng", "thư giãn, thả lỏng", "听音乐可以让人放松。", "Tīng yīnyuè kěyǐ ràng rén fàngsōng.", "Nghe nhạc có thể giúp người ta thư giãn.", "Động từ"],
    ["拍", "pāi", "chụp (ảnh)", "我们一起拍张照吧。", "Wǒmen yìqǐ pāi zhāng zhào ba.", "Chúng ta cùng chụp một tấm ảnh đi.", "Động từ"],
    ["压力", "yālì", "áp lực", "现在年轻人的工作压力很大。", "Xiànzài niánqīng rén de gōngzuò yālì hěn dà.", "Áp lực công việc của người trẻ hiện nay rất lớn.", "Danh từ"],
    ["回忆", "huíyì", "hồi ức, nhớ lại", "这首歌勾起了我的回忆。", "Zhè shǒu gē gōuqǐ le wǒ de huíyì.", "Bài hát này đã gợi lại hồi ức của tôi.", "Danh từ/Động từ"],
    ["发生", "fāshēng", "xảy ra", "这里发生了什么事？", "Zhèlǐ fāshēng le shénme shì?", "Ở đây đã xảy ra chuyện gì?", "Động từ"],
    ["成为", "chéngwéi", "trở thành", "他想成为一名医生。", "Tā xiǎng chéngwéi yì míng yīshēng.", "Cậu ấy muốn trở thành một bác sĩ.", "Động từ"],
    ["只要", "zhǐyào", "chỉ cần", "只要努力，就能成功。", "Zhǐyào nǔlì, jiù néng chénggōng.", "Chỉ cần nỗ lực thì sẽ thành công.", "Liên từ"],
    ["师傅", "shīfu", "sư phụ, bác tài, thợ", "师傅，请去火车站。", "Shīfu, qǐng qù huǒchēzhàn.", "Bác tài, xin đến ga tàu hỏa.", "Danh từ"],
    ["大使馆", "dàshǐguǎn", "đại sứ quán", "我要去大使馆办签证。", "Wǒ yào qù dàshǐguǎn bàn qiānzhèng.", "Tôi phải đến đại sứ quán làm visa.", "Danh từ"],
    ["堵车", "dǔchē", "tắc đường", "前面堵车了，我们换条路吧。", "Qiánmiàn dǔchē le, wǒmen huàn tiáo lù ba.", "Phía trước tắc đường rồi, chúng ta đổi đường khác đi.", "Động từ"],
    ["距离", "jùlí", "khoảng cách", "我家距离学校很近。", "Wǒ jiā jùlí xuéxiào hěn jìn.", "Nhà tôi cách trường rất gần.", "Danh từ"],
    ["耐心", "nàixīn", "kiên nhẫn", "教孩子需要很大的耐心。", "Jiāo háizi xūyào hěn dà de nàixīn.", "Dạy trẻ em cần sự kiên nhẫn rất lớn.", "Danh từ/Tính từ"],
    ["首都", "shǒudū", "thủ đô", "河内是越南的首都。", "Hénèi shì Yuènán de shǒudū.", "Hà Nội là thủ đô của Việt Nam.", "Danh từ"],
    ["保持", "bǎochí", "giữ, duy trì", "我们要保持联系。", "Wǒmen yào bǎochí liánxì.", "Chúng ta phải giữ liên lạc.", "Động từ"],
    ["可不是", "kěbúshì", "đúng vậy, chính xác", "可不是嘛，今天真冷！", "Kěbúshì ma, jīntiān zhēn lěng!", "Đúng vậy mà, hôm nay lạnh thật!", "Cụm từ/Phó từ"],
    ["生命", "shēngmìng", "sinh mệnh, sự sống", "生命是非常宝贵的。", "Shēngmìng shì fēicháng bǎoguì de.", "Sinh mệnh là vô cùng quý giá.", "Danh từ"],
    ["缺少", "quēshǎo", "thiếu sót, thiếu", "我们缺少一些经验。", "Wǒmen quēshǎo yìxiē jīngyàn.", "Chúng ta thiếu một chút kinh nghiệm.", "Động từ"],
    ["到处", "dàochù", "khắp nơi", "公园里到处都是人。", "Gōngyuán lǐ dàochù dōu shì rén.", "Trong công viên đâu đâu cũng là người.", "Phó từ"],
    ["态度", "tàidu", "thái độ", "他的服务态度很好。", "Tā de fúwù tàidu hěn hǎo.", "Thái độ phục vụ của anh ấy rất tốt.", "Danh từ"],
    ["因此", "yīncǐ", "do đó, vì vậy", "他生病了，因此没来上课。", "Tā shēngbìng le, yīncǐ méi lái shàngkè.", "Anh ấy ốm rồi, do đó không đến lớp.", "Liên từ"],
    ["炒鱿鱼", "chǎoyóuyú", "sa thải, đuổi việc", "他上个月被老板炒鱿鱼了。", "Tā shàng gè yuè bèi lǎobǎn chǎoyóuyú le.", "Tháng trước anh ấy bị ông chủ sa thải rồi.", "Động từ"],
    ["行为", "xíngwéi", "hành vi", "我们要对自己的行为负责。", "Wǒmen yào duì zìjǐ de xíngwéi fùzé.", "Chúng ta phải chịu trách nhiệm cho hành vi của mình.", "Danh từ"],
    ["科学", "kēxué", "khoa học", "他对科学很感兴趣。", "Tā duì kēxué hěn gǎn xìngqù.", "Anh ấy rất có hứng thú với khoa học.", "Danh từ/Tính từ"],
    ["证明", "zhèngmíng", "chứng minh", "事实证明他是对的。", "Shìshí zhèngmíng tā shì duì de.", "Thực tế chứng minh anh ấy là đúng.", "Động từ/Danh từ"],
    ["往往", "wǎngwǎng", "thường thường, hay", "周末我往往在家里看书。", "Zhōumò wǒ wǎngwǎng zài jiālǐ kàn shū.", "Cuối tuần tôi thường ở nhà đọc sách.", "Phó từ"],
    ["阳光", "yángguāng", "ánh nắng / vui vẻ", "今天的阳光很明媚。", "Jīntiān de yángguāng hěn míngmèi.", "Ánh nắng hôm nay rất tươi sáng.", "Danh từ/Tính từ"],
    ["积极", "jījí", "tích cực", "我们要积极面对困难。", "Wǒmen yào jījí miànduì kùnnan.", "Chúng ta phải tích cực đối mặt khó khăn.", "Tính từ"],
    ["特点", "tèdiǎn", "đặc điểm", "这种产品的特点是什么？", "Zhè zhǒng chǎnpǐn de tèdiǎn shì shénme?", "Đặc điểm của loại sản phẩm này là gì?", "Danh từ"],
    ["工业区", "gōngyèqū", "khu công nghiệp", "他在附近的工业区上班。", "Tā zài fùjìn de gōngyèqū shàngbān.", "Anh ấy làm việc ở khu công nghiệp gần đây.", "Danh từ"]
],
  "hsk9": [
    ["饼干", "bǐnggān", "bánh quy", "这盒饼干很好吃。", "Zhè hé bǐnggān hěn hǎochī.", "Hộp bánh quy này rất ngon.", "Danh từ"],
    ["难道", "nándào", "lẽ nào, chẳng lẽ", "你难道不知道这件事吗？", "Nǐ nándào bù zhīdào zhè jiàn shì ma?", "Lẽ nào bạn không biết chuyện này?", "Phó từ"],
    ["得", "děi", "phải", "时间不早了，我得走了。", "Shíjiān bù zǎo le, wǒ děi zǒu le.", "Trời không còn sớm nữa, tôi phải đi rồi.", "Động từ năng nguyện"],
    ["坚持", "jiānchí", "kiên trì", "只要坚持，就一定会成功。", "Zhǐyào jiānchí, jiù yídìng huì chénggōng.", "Chỉ cần kiên trì, thì nhất định sẽ thành công.", "Động từ"],
    ["放弃", "fàngqì", "từ bỏ", "不要轻易放弃你的梦想。", "Búyào qīngyì fàngqì nǐ de mèngxiǎng.", "Đừng dễ dàng từ bỏ ước mơ của bạn.", "Động từ"],
    ["主意", "zhǔyi", "ý kiến, chủ ý", "这个主意不错。", "Zhège zhǔyi búcuò.", "Chủ ý này không tồi.", "Danh từ"],
    ["网球", "wǎngqiú", "quần vợt, tennis", "他喜欢打网球。", "Tā xǐhuan dǎ wǎngqiú.", "Cậu ấy thích chơi tennis.", "Danh từ"],
    ["国际", "guójì", "quốc tế", "这是一家国际公司。", "Zhè shì yì jiā guójì gōngsī.", "Đây là một công ty quốc tế.", "Tính từ"],
    ["轻松", "qīngsōng", "nhẹ nhõm, thư giãn", "考完试，我觉得很轻松。", "Kǎo wán shì, wǒ juéde hěn qīngsōng.", "Thi xong, tôi cảm thấy rất nhẹ nhõm.", "Tính từ"],
    ["赢", "yíng", "thắng", "这场比赛我们赢了。", "Zhè chǎng bǐsài wǒmen yíng le.", "Trận đấu này chúng tôi thắng rồi.", "Động từ"],
    ["随便", "suíbiàn", "tùy tiện, tùy ý", "请随便坐。", "Qǐng suíbiàn zuò.", "Mời ngồi tùy ý.", "Tính từ/Phó từ"],
    ["汗", "hàn", "mồ hôi", "他出了很多汗。", "Tā chū le hěn duō hàn.", "Anh ấy đổ rất nhiều mồ hôi.", "Danh từ"],
    ["通过", "tōngguò", "thông qua", "他通过了汉语考试。", "Tā tōngguò le Hànyǔ kǎoshì.", "Anh ấy đã thông qua kỳ thi tiếng Hán.", "Động từ/Giới từ"],
    ["篇", "piān", "bài (lượng từ của văn bản)", "这是一篇好文章。", "Zhè shì yì piān hǎo wénzhāng.", "Đây là một bài văn hay.", "Lượng từ"],
    ["作家", "zuòjiā", "nhà văn", "他是一位著名的作家。", "Tā shì yí wèi zhùmíng de zuòjiā.", "Ông ấy là một nhà văn nổi tiếng.", "Danh từ"],
    ["当时", "dāngshí", "lúc đó", "当时我不在家。", "Dāngshí wǒ bú zài jiā.", "Lúc đó tôi không có ở nhà.", "Danh từ"],
    ["可是", "kěshì", "nhưng", "我想去，可是没时间。", "Wǒ xiǎng qù, kěshì méi shíjiān.", "Tôi muốn đi, nhưng không có thời gian.", "Liên từ"],
    ["正确", "zhèngquè", "chính xác", "你的答案是正确的。", "Nǐ de dá'àn shì zhèngquè de.", "Đáp án của bạn là chính xác.", "Tính từ"],
    ["理想", "lǐxiǎng", "lý tưởng", "我的理想是当一名老师。", "Wǒ de lǐxiǎng shì dāng yì míng lǎoshī.", "Lý tưởng của tôi là làm một giáo viên.", "Danh từ/Tính từ"],
    ["勇敢", "yǒnggǎn", "dũng cảm", "他是一个勇敢的人。", "Tā shì yí ge yǒnggǎn de rén.", "Anh ấy là một người dũng cảm.", "Tính từ"],
    ["结果", "jiéguǒ", "kết quả", "我们还在等考试结果。", "Wǒmen hái zài děng kǎoshì jiéguǒ.", "Chúng tôi vẫn đang đợi kết quả thi.", "Danh từ"],
    ["失败", "shībài", "thất bại", "失败是成功之母。", "Shībài shì chénggōng zhī mǔ.", "Thất bại là mẹ thành công.", "Động từ/Danh từ"],
    ["过程", "guòchéng", "quá trình", "学习的过程很辛苦。", "Xuéxí de guòchéng hěn xīnkǔ.", "Quá trình học tập rất vất vả.", "Danh từ"],
    ["至少", "zhìshǎo", "ít nhất", "他至少三十岁了。", "Tā zhìshǎo sānshí suì le.", "Anh ấy ít nhất cũng 30 tuổi rồi.", "Phó từ"],
    ["总结", "zǒngjié", "tổng kết", "请你总结一下今天的内容。", "Qǐng nǐ zǒngjié yíxià jīntiān de nèiróng.", "Xin hãy tổng kết lại nội dung ngày hôm nay.", "Động từ"],
    ["取", "qǔ", "lấy", "我去银行取钱。", "Wǒ qù yínháng qǔ qián.", "Tôi đến ngân hàng lấy tiền.", "Động từ"],
    ["经历", "jīnglì", "trải nghiệm, trải qua", "这是一段难忘的经历。", "Zhè shì yí duàn nánwàng de jīnglì.", "Đây là một trải nghiệm khó quên.", "Danh từ/Động từ"],
    ["许多", "xǔduō", "rất nhiều", "这里有许多漂亮的花。", "Zhèlǐ yǒu xǔduō piàoliang de huā.", "Ở đây có rất nhiều hoa đẹp.", "Tính từ"],
    ["区别", "qūbié", "phân biệt, sự khác biệt", "你知道这两个词的区别吗？", "Nǐ zhīdào zhè liǎng ge cí de qūbié ma?", "Bạn có biết sự khác biệt của hai từ này không?", "Danh từ/Động từ"],
    ["暂时", "zànshí", "tạm thời", "我暂时没有其他问题。", "Wǒ zànshí méiyǒu qítā wèntí.", "Tôi tạm thời không có câu hỏi nào khác.", "Phó từ"],
    ["面对", "miànduì", "đối mặt", "我们要勇敢面对困难。", "Wǒmen yào yǒnggǎn miànduì kùnnan.", "Chúng ta phải dũng cảm đối mặt với khó khăn.", "Động từ"]
  ],
  "hsk10": [
    ["礼拜天", "lǐbàitiān", "Chủ nhật", "我们礼拜天去爬山。", "Wǒmen lǐbàitiān qù páshān.", "Chủ nhật chúng tôi đi leo núi.", "Danh từ"],
    ["空儿", "kòngr", "thời gian rảnh", "你明天有空儿吗？", "Nǐ míngtiān yǒu kòngr ma?", "Ngày mai bạn có rảnh không?", "Danh từ"],
    ["母亲", "mǔqīn", "người mẹ", "我的母亲是一名医生。", "Wǒ de mǔqīn shì yì míng yīshēng.", "Mẹ của tôi là một bác sĩ.", "Danh từ"],
    ["不过", "búguò", "nhưng, có điều", "这件衣服好看，不过太贵了。", "Zhè jiàn yīfu hǎokàn, búguò tài guì le.", "Bộ quần áo này đẹp, có điều quá đắt.", "Liên từ/Phó từ"],
    ["永远", "yǒngyuǎn", "mãi mãi", "我会永远记住你的好。", "Wǒ huì yǒngyuǎn jìzhu nǐ de hǎo.", "Tôi sẽ mãi mãi nhớ sự tốt bụng của bạn.", "Phó từ"],
    ["方向", "fāngxiàng", "phương hướng", "你走错方向了。", "Nǐ zǒu cuò fāngxiàng le.", "Bạn đi nhầm hướng rồi.", "Danh từ"],
    ["优秀", "yōuxiù", "xuất sắc", "他是一个非常优秀的学生。", "Tā shì yí ge fēicháng yōuxiù de xuéshēng.", "Cậu ấy là một học sinh vô cùng xuất sắc.", "Tính từ"],
    ["硕士", "shuòshì", "thạc sĩ", "他在读硕士研究生。", "Tā zài dú shuòshì yánjiūshēng.", "Anh ấy đang học nghiên cứu sinh thạc sĩ.", "Danh từ"],
    ["翻译", "fānyì", "dịch, phiên dịch", "请把这句话翻译成汉语。", "Qǐng bǎ zhè jù huà fānyì chéng Hànyǔ.", "Xin hãy dịch câu này sang tiếng Hán.", "Động từ/Danh từ"],
    ["确实", "quèshí", "thực sự, quả thật", "他确实是个好人。", "Tā quèshí shì ge hǎorén.", "Anh ấy quả thật là một người tốt.", "Phó từ"],
    ["兴奋", "xīngfèn", "hưng phấn, hào hứng", "听到这个消息，他很兴奋。", "Tīngdào zhège xiāoxi, tā hěn xīngfèn.", "Nghe được tin này, anh ấy rất hào hứng.", "Tính từ"],
    ["拉", "lā", "kéo", "他拉着我的手。", "Tā lā zhe wǒ de shǒu.", "Anh ấy kéo tay tôi.", "Động từ"],
    ["建议", "jiànyì", "kiến nghị, đề nghị", "我建议你多休息。", "Wǒ jiànyì nǐ duō xiūxi.", "Tôi đề nghị bạn nghỉ ngơi nhiều hơn.", "Động từ/Danh từ"],
    ["职业", "zhíyè", "nghề nghiệp", "你的职业是什么？", "Nǐ de zhíyè shì shénme?", "Nghề nghiệp của bạn là gì?", "Danh từ"],
    ["关键", "guānjiàn", "mấu chốt", "解决问题的关键是沟通。", "Jiějué wèntí de guānjiàn shì gōutōng.", "Mấu chốt của việc giải quyết vấn đề là giao tiếp.", "Danh từ/Tính từ"],
    ["将来", "jiānglái", "tương lai", "你将来想做什么？", "Nǐ jiānglái xiǎng zuò shénme?", "Tương lai bạn muốn làm gì?", "Danh từ"],
    ["发展", "fāzhǎn", "phát triển", "这座城市发展得很快。", "Zhè zuò chéngshì fāzhǎn de hěn kuài.", "Thành phố này phát triển rất nhanh.", "Động từ/Danh từ"],
    ["躺", "tǎng", "nằm", "他正躺在床上看书。", "Tā zhèng tǎng zài chuáng shàng kàn shū.", "Anh ấy đang nằm trên giường đọc sách.", "Động từ"],
    ["困", "kùn", "buồn ngủ", "我有点儿困了。", "Wǒ yǒudiǎnr kùn le.", "Tôi hơi buồn ngủ rồi.", "Tính từ"],
    ["经济", "jīngjì", "kinh tế", "这个国家的经济发展很好。", "Zhège guójiā de jīngjì fāzhǎn hěn hǎo.", "Nền kinh tế của quốc gia này phát triển rất tốt.", "Danh từ"],
    ["条件", "tiáojiàn", "điều kiện", "我们公司的条件很好。", "Wǒmen gōngsī de tiáojiàn hěn hǎo.", "Điều kiện của công ty chúng tôi rất tốt.", "Danh từ"],
    ["富", "fù", "giàu có", "他是一个很富的人。", "Tā shì yí ge hěn fù de rén.", "Ông ấy là một người rất giàu có.", "Tính từ"],
    ["穷", "qióng", "nghèo", "即使很穷，他也很开心。", "Jíshǐ hěn qióng, tā yě hěn kāixīn.", "Cho dù rất nghèo, anh ấy cũng rất vui vẻ.", "Tính từ"],
    ["等", "děng", "vân vân, đợi", "我喜欢苹果、香蕉等水果。", "Wǒ xǐhuan píngguǒ, xiāngjiāo děng shuǐguǒ.", "Tôi thích các loại trái cây như táo, chuối, v.v.", "Trợ từ/Động từ"],
    ["由于", "yóuyú", "bởi vì, do", "由于天气原因，航班取消了。", "Yóuyú tiānqì yuányīn, hángbān qǔxiāo le.", "Do nguyên nhân thời tiết, chuyến bay đã bị hủy.", "Liên từ/Giới từ"],
    ["比如", "bǐrú", "ví dụ như", "我喜欢运动，比如游泳、跑步。", "Wǒ xǐhuan yùndòng, bǐrú yóuyǒng, pǎobù.", "Tôi thích vận động, ví dụ như bơi lội, chạy bộ.", "Động từ"],
    ["橡皮", "xiàngpí", "cục tẩy", "你能借我一块橡皮吗？", "Nǐ néng jiè wǒ yí kuài xiàngpí ma?", "Bạn có thể cho tôi mượn một cục tẩy không?", "Danh từ"],
    ["糖", "táng", "đường, kẹo", "我不喜欢吃太多的糖。", "Wǒ bù xǐhuan chī tài duō de táng.", "Tôi không thích ăn quá nhiều đường.", "Danh từ"],
    ["低", "dī", "thấp", "这里的温度很低。", "Zhèlǐ de wēndù hěn dī.", "Nhiệt độ ở đây rất thấp.", "Tính từ"],
    ["答案", "dá'àn", "đáp án", "你知道这个问题的答案吗？", "Nǐ zhīdào zhège wèntí de dá'àn ma?", "Bạn có biết đáp án của câu hỏi này không?", "Danh từ"]
  ],
 "hsk11": [
   ["流利", "liúlì", "lưu loát, trôi chảy", "你来中国才一年，汉语就说得这么流利。", "Nǐ lái Zhōngguó cái yì nián, Hànyǔ jiù shuō de zhème liúlì.", "Bạn đến Trung Quốc mới một năm mà tiếng Hán đã nói lưu loát như vậy.", "Tính từ"],
    ["厉害", "lìhai", "lợi hại, giỏi, nghiêm trọng", "他玩游戏非常厉害。", "Tā wán yóuxì fēicháng lìhai.", "Anh ấy chơi game rất giỏi/lợi hại.", "Tính từ"],
    ["准确", "zhǔnquè", "chính xác, chuẩn, đúng", "我的语法不太好，很多句子说得不太准确。", "Wǒ de yǔfǎ bú tài hǎo, hěn duō jùzi shuō de bú tài zhǔnquè.", "Ngữ pháp của tôi không tốt lắm, nhiều câu nói không được chuẩn xác.", "Tính từ"],
    ["迎接", "yíngjiē", "chào đón", "我们去机场迎接客人。", "Wǒmen qù jīchǎng yíngjiē kèrén.", "Chúng tôi ra sân bay chào đón khách.", "Động từ"],
    ["语法", "yǔfǎ", "ngữ pháp", "汉语语法其实不太难。", "Hànyǔ yǔfǎ qíshí bú tài nán.", "Ngữ pháp tiếng Trung thực ra không quá khó.", "Danh từ"],
    ["词语", "cíyǔ", "từ ngữ, từ vựng", "多看中文报纸能学到很多新词语。", "Duō kàn Zhōngwén bàozhǐ néng xuédào hěn duō xīn cíyǔ.", "Đọc nhiều báo tiếng Trung có thể học được rất nhiều từ vựng mới.", "Danh từ"],
    ["连", "lián", "ngay cả (... cũng/đều)", "这个问题太难了，连老师也不会。", "Zhège wèntí tài nán le, lián lǎoshī yě bú huì.", "Vấn đề này khó quá, ngay cả giáo viên cũng không biết.", "Giới từ"],
    ["阅读", "yuèdú", "đọc, đọc hiểu", "这次阅读考试的题太多了。", "Zhè cì yuèdú kǎoshì de tí tài duō le.", "Đề thi đọc hiểu lần này nhiều quá.", "Động từ/Danh từ"],
    ["听力", "tīnglì", "nghe hiểu", "我要多练习听力。", "Wǒ yào duō liànxí tīnglì.", "Tôi phải luyện tập nghe hiểu nhiều hơn.", "Danh từ"],
    ["书写", "shūxiě", "viết", "他的书写很整齐。", "Tā de shūxiě hěn zhěngqí.", "Chữ viết của anh ấy rất ngay ngắn.", "Động từ/Danh từ"],
    ["口语", "kǒuyǔ", "khẩu ngữ", "我想提高我的汉语口语。", "Wǒ xiǎng tígāo wǒ de Hànyǔ kǒuyǔ.", "Tôi muốn nâng cao khẩu ngữ tiếng Trung của mình.", "Danh từ"],
    ["题", "tí", "đề, câu", "这道题我不知道怎么做。", "Zhè dào tí wǒ bù zhīdào zěnme zuò.", "Câu hỏi này tôi không biết làm thế nào.", "Danh từ"],
    ["来得及", "láidejí", "kịp, còn kịp", "两个小时的时间应该来得及吧？", "Liǎng ge xiǎoshí de shíjiān yīnggāi láidejí ba?", "Thời gian hai tiếng đồng hồ chắc là kịp nhỉ?", "Động từ"],
    ["来不及", "láibují", "không kịp", "快点儿走，要来不及了。", "Kuài diǎnr zǒu, yào láibují le.", "Đi nhanh lên, sắp không kịp rồi.", "Động từ"],
    ["忙着", "mángzhe", "bận làm gì", "他正忙着准备明天的考试。", "Tā zhèng mángzhe zhǔnběi míngtiān de kǎoshì.", "Anh ấy đang bận chuẩn bị cho kỳ thi ngày mai.", "Động từ"],
    ["复杂", "fùzá", "phức tạp, rắc rối", "我先做了比较复杂的题。", "Wǒ xiān zuò le bǐjiào fùzá de tí.", "Tôi đã làm những câu tương đối phức tạp trước.", "Tính từ"],
    ["只好", "zhǐhǎo", "đành phải, buộc phải", "最后只好放弃了。", "Zuìhòu zhǐhǎo fàngqì le.", "Cuối cùng đành phải từ bỏ.", "Phó từ"],
    ["否则", "fǒuzé", "nếu không thì, bằng không", "考试要认真，否则会做错。", "Kǎoshì yào rènzhēn, fǒuzé huì zuò cuò.", "Thi cử phải nghiêm túc, nếu không thì sẽ làm sai.", "Liên từ"],
    ["填空", "tiánkòng", "điền vào chỗ trống", "有几个填空题不会做。", "Yǒu jǐ ge tiánkòng tí bú huì zuò.", "Có mấy câu điền vào chỗ trống không biết làm.", "Động từ"],
    ["猜", "cāi", "đoán", "结果一个都没猜对。", "Jiéguǒ yí ge dōu méi cāi duì.", "Kết quả là không đoán đúng một câu nào.", "Động từ"],
    ["随便", "suíbiàn", "thoải mái, tuỳ", "我就随便猜了一个答案。", "Wǒ jiù suíbiàn cāi le yí ge dá'àn.", "Tôi liền đoán bừa/tùy tiện một đáp án.", "Tính từ/Phó từ"],
    ["客厅", "kètīng", "phòng khách", "我家客厅很大。", "Wǒ jiā kètīng hěn dà.", "Phòng khách nhà tôi rất lớn.", "Danh từ"],
    ["无论", "wúlùn", "bất luận, bất kể", "无论多忙，他都坚持锻炼。", "Wúlùn duō máng, tā dōu jiānchí duànliàn.", "Dù bận thế nào, anh ấy đều kiên trì rèn luyện.", "Liên từ"],
    ["杂志", "zázhì", "tạp chí", "桌子上有一本杂志。", "Zhuōzi shàng yǒu yì běn zázhì.", "Trên bàn có một cuốn tạp chí.", "Danh từ"],
    ["著名", "zhùmíng", "nổi tiếng", "他是一位著名的作家。", "Tā shì yí wèi zhùmíng de zuòjiā.", "Ông ấy là một nhà văn nổi tiếng.", "Tính từ"],
    ["页", "yè", "trang", "这本书有三百页。", "Zhè běn shū yǒu sān bǎi yè.", "Cuốn sách này có 300 trang.", "Lượng từ"],
    ["增加", "zēngjiā", "tăng thêm", "阅读能增加我们的知识。", "Yuèdú néng zēngjiā wǒmen de zhīshi.", "Đọc sách có thể tăng thêm kiến thức cho chúng ta.", "Động từ"],
    ["文章", "wénzhāng", "bài văn, bài báo", "这篇文章写得很好。", "Zhè piān wénzhāng xiě de hěn hǎo.", "Bài văn này viết rất hay.", "Danh từ"],
    ["之", "zhī", "của (dùng nối từ bổ nghĩa và được bổ nghĩa)", "三分之一", "Sān fēn zhī yī", "Một phần ba", "Trợ từ"],
    ["内容", "nèiróng", "nội dung", "这篇文章的内容很丰富。", "Zhè piān wénzhāng de nèiróng hěn fēngfù.", "Nội dung của bài viết này rất phong phú.", "Danh từ"],
    ["然而", "rán'ér", "nhưng, song", "他很聪明，然而不太努力。", "Tā hěn cōngming, rán'ér bú tài nǔlì.", "Anh ấy rất thông minh, nhưng không nỗ lực lắm.", "Liên từ"],
    ["看法", "kànfǎ", "quan điểm, cách nhìn", "每个人都有自己的看法。", "Měi ge rén dōu yǒu zìjǐ de kànfǎ.", "Mỗi người đều có quan điểm riêng của mình.", "Danh từ"],
    ["相同", "xiāngtóng", "giống nhau, như nhau", "我们的爱好相同。", "Wǒmen de àihào xiāngtóng.", "Sở thích của chúng tôi giống nhau.", "Tính từ"],
    ["顺序", "shùnxù", "trật tự, thứ tự", "请按顺序排队。", "Qǐng àn shùnxù páiduì.", "Xin hãy xếp hàng theo thứ tự.", "Danh từ"],
    ["表示", "biǎoshì", "biểu thị, có ý nghĩa", "点头表示同意。", "Diǎntóu biǎoshì tóngyì.", "Gật đầu biểu thị sự đồng ý.", "Động từ"],
    ["养成", "yǎngchéng", "hình thành, tạo (thói quen)", "从小要养成好习惯。", "Cóngxiǎo yào yǎngchéng hǎo xíguàn.", "Từ nhỏ phải hình thành thói quen tốt.", "Động từ"],
    ["同时", "tóngshí", "đồng thời, hơn nữa", "阅读的同时，还会有很多新发现。", "Yuèdú de tóngshí, hái huì yǒu hěn duō xīn fāxiàn.", "Đồng thời với việc đọc, còn có thể có nhiều phát hiện mới.", "Liên từ/Danh từ"],
    ["精彩", "jīngcǎi", "tuyệt vời, xuất sắc", "这场比赛非常精彩。", "Zhè chǎng bǐsài fēicháng jīngcǎi.", "Trận đấu này vô cùng đặc sắc.", "Tính từ"]
 ],
  "hsk12": [
    ["航班", "hángbān", "chuyến bay", "您的航班马上就要起飞了。", "Nín de hángbān mǎshàng jiù yào qǐfēi le.", "Chuyến bay của ngài sắp cất cánh rồi.", "Danh từ"],
    ["乘坐", "chéngzuò", "đi, ngồi (xe, tàu, máy bay)", "欢迎乘坐本次航班。", "Huānyíng chéngzuò běn cì hángbān.", "Chào mừng đi trên chuyến bay lần này.", "Động từ"],
    ["推迟", "tuīchí", "trì hoãn, lùi lại", "因为天气原因，会议推迟了。", "Yīnwèi tiānqì yuányīn, huìyì tuīchí le.", "Vì nguyên nhân thời tiết, cuộc họp đã bị lùi lại.", "Động từ"],
    ["降落", "jiàngluò", "hạ cánh", "飞机还有十分钟降落。", "Fēijī hái yǒu shí fēnzhōng jiàngluò.", "Máy bay còn 10 phút nữa hạ cánh.", "Động từ"],
    ["广播", "guǎngbō", "phát thanh", "听广播可以提高听力。", "Tīng guǎngbō kěyǐ tígāo tīnglì.", "Nghe phát thanh có thể nâng cao kỹ năng nghe.", "Danh từ/Động từ"],
    ["于是", "yúshì", "thế là, ngay sau đó", "太晚了，于是我就在酒店住下了。", "Tài wǎn le, yúshì wǒ jiù zài jiǔdiàn zhù xià le.", "Muộn quá rồi, thế là tôi ở lại khách sạn luôn.", "Liên từ"],
    ["无论", "wúlùn", "bất luận, dù cho", "无论多难，我都要坚持。", "Wúlùn duō nán, wǒ dōu yào jiānchí.", "Dù khó khăn thế nào, tôi cũng phải kiên trì.", "Liên từ"],
    ["随着", "suízhe", "cùng với", "随着时间的发展，城市变化很大。", "Suízhe shíjiān de fāzhǎn, chéngshì biànhuà hěn dà.", "Cùng với sự phát triển của thời gian, thành phố thay đổi rất nhiều.", "Giới từ"],
    ["凉快", "liángkuai", "mát mẻ", "秋天的天气很凉快。", "Qiūtiān de tiānqì hěn liángkuai.", "Thời tiết mùa thu rất mát mẻ.", "Tính từ"],
    ["暖和", "nuǎnhuo", "ấm áp", "春天到了，天气暖和了。", "Chūntiān dào le, tiānqì nuǎnhuo le.", "Mùa xuân đến rồi, thời tiết ấm áp rồi.", "Tính từ"],
    ["严格", "yángé", "nghiêm khắc", "老师对我们的要求很严格。", "Lǎoshī duì wǒmen de yāoqiú hěn yángé.", "Giáo viên yêu cầu đối với chúng tôi rất nghiêm khắc.", "Tính từ"],
    ["准确", "zhǔnquè", "chính xác", "你的发音非常准确。", "Nǐ de fāyīn fēicháng zhǔnquè.", "Phát âm của bạn vô cùng chính xác.", "Tính từ"],
    ["左右", "zuǒyòu", "khoảng, chừng", "他大概三十岁左右。", "Tā dàgài sānshí suì zuǒyòu.", "Anh ấy khoảng chừng 30 tuổi.", "Danh từ"],
    ["基础", "jīchǔ", "cơ sở, nền tảng", "学习汉语，基础很重要。", "Xuéxí Hànyǔ, jīchǔ hěn zhòngyào.", "Học tiếng Hán, nền tảng rất quan trọng.", "Danh từ"],
    ["语法", "yǔfǎ", "ngữ pháp", "汉语的语法不太难。", "Hànyǔ de yǔfǎ bú tài nán.", "Ngữ pháp tiếng Hán không quá khó.", "Danh từ"],
    ["词语", "cíyǔ", "từ ngữ", "请用这些词语造句。", "Qǐng yòng zhèxiē cíyǔ zàojù.", "Xin hãy dùng những từ ngữ này để đặt câu.", "Danh từ"],
    ["预习", "yùxí", "chuẩn bị bài", "上课前要好好预习。", "Shàngkè qián yào hǎohǎo yùxí.", "Trước khi lên lớp phải chuẩn bị bài thật tốt.", "Động từ"],
    ["阅读", "yuèdú", "đọc hiểu", "我的阅读能力还需要提高。", "Wǒ de yuèdú nénglì hái xūyào tígāo.", "Năng lực đọc hiểu của tôi còn cần nâng cao.", "Động từ/Danh từ"],
    ["复杂", "fùzá", "phức tạp", "这个问题越来越复杂了。", "Zhège wèntí yuè lái yuè fùzá le.", "Vấn đề này càng ngày càng phức tạp rồi.", "Tính từ"],
    ["讨论", "tǎolùn", "thảo luận", "我们正在讨论下个月的计划。", "Wǒmen zhèngzài tǎolùn xià ge yuè de jìhuà.", "Chúng tôi đang thảo luận kế hoạch của tháng sau.", "Động từ"],
    ["解释", "jiěshì", "giải thích", "请听我解释。", "Qǐng tīng wǒ jiěshì.", "Xin hãy nghe tôi giải thích.", "Động từ"],
    ["详细", "xiángxì", "chi tiết, tường tận", "请把这件事详细地说一遍。", "Qǐng bǎ zhè jiàn shì xiángxì de shuō yí biàn.", "Xin hãy kể lại chuyện này một cách chi tiết.", "Tính từ"],
    ["误会", "wùhuì", "hiểu lầm", "这完全是一个误会。", "Zhè wánquán shì yí ge wùhuì.", "Đây hoàn toàn là một sự hiểu lầm.", "Danh từ/Động từ"],
    ["杂志", "zázhì", "tạp chí", "我喜欢看时尚杂志。", "Wǒ xǐhuan kàn shíshàng zázhì.", "Tôi thích xem tạp chí thời trang.", "Danh từ"],
    ["支持", "zhīchí", "ủng hộ", "感谢大家的支持。", "Gǎnxiè dàjiā de zhīchí.", "Cảm ơn sự ủng hộ của mọi người.", "Động từ/Danh từ"]
  ],
  "hsk13": [
    ["到底", "dàodǐ", "rốt cuộc", "你到底去不去？", "Nǐ dàodǐ qù bú qù?", "Rốt cuộc bạn có đi hay không?", "Phó từ"],
    ["既然", "jìrán", "đã, nếu đã", "既然来了，就吃完饭再走吧。", "Jìrán lái le, jiù chī wán fàn zài zǒu ba.", "Nếu đã đến rồi, thì ăn cơm xong hẵng đi.", "Liên từ"],
    ["偶尔", "ǒu'ěr", "thỉnh thoảng", "我偶尔会去那家咖啡馆。", "Wǒ ǒu'ěr huì qù nà jiā kāfēiguǎn.", "Thỉnh thoảng tôi có đến quán cà phê đó.", "Phó từ"],
    ["也许", "yěxǔ", "có lẽ", "也许他是对的。", "Yěxǔ tā shì duì de.", "Có lẽ anh ấy đúng.", "Phó từ"],
    ["并且", "bìngqiě", "đồng thời, và", "他聪明并且很努力。", "Tā cōngming bìngqiě hěn nǔlì.", "Anh ấy thông minh và rất chăm chỉ.", "Liên từ"],
    ["力气", "lìqi", "sức lực", "我没有力气搬这个箱子。", "Wǒ méiyǒu lìqi bān zhège xiāngzi.", "Tôi không có sức để bê cái thùng này.", "Danh từ"],
    ["任务", "rènwu", "nhiệm vụ", "今天的任务比较重。", "Jīntiān de rènwu bǐjiào zhòng.", "Nhiệm vụ hôm nay tương đối nặng.", "Danh từ"],
    ["意见", "yìjiàn", "ý kiến", "大家有什么意见？", "Dàjiā yǒu shénme yìjiàn?", "Mọi người có ý kiến gì không?", "Danh từ"],
    ["达到", "dádào", "đạt đến, đạt được", "我们的目标已经达到了。", "Wǒmen de mùbiāo yǐjīng dádào le.", "Mục tiêu của chúng ta đã đạt được rồi.", "Động từ"],
    ["报道", "bàodào", "đưa tin, bài báo", "新闻报道了这件事。", "Xīnwén bàodào le zhè jiàn shì.", "Tin tức đã đưa tin về chuyện này.", "Động từ/Danh từ"],
    ["报名", "bàomíng", "đăng ký", "我想报名参加比赛。", "Wǒ xiǎng bàomíng cānjiā bǐsài.", "Tôi muốn đăng ký tham gia thi đấu.", "Động từ"],
    ["抱", "bào", "ôm", "母亲抱着孩子。", "Mǔqīn bào zhe háizi.", "Người mẹ đang ôm đứa con.", "Động từ"],
    ["抱歉", "bàoqiàn", "xin lỗi, áy náy", "很抱歉，我迟到了。", "Hěn bàoqiàn, wǒ chídào le.", "Rất xin lỗi, tôi đến muộn rồi.", "Tính từ"],
    ["笨", "bèn", "ngốc, ngốc nghếch", "我真是太笨了。", "Wǒ zhēn shì tài bèn le.", "Tôi đúng là ngốc quá đi.", "Tính từ"],
    ["遍", "biàn", "lần, lượt (từ đầu đến cuối)", "请再说一遍。", "Qǐng zài shuō yí biàn.", "Xin hãy nói lại một lần nữa.", "Lượng từ"],
    ["表格", "biǎogé", "bảng biểu", "请填写这张表格。", "Qǐng tiánxiě zhè zhāng biǎogé.", "Xin hãy điền vào bảng biểu này.", "Danh từ"],
    ["表示", "biǎoshì", "biểu thị, bày tỏ", "他对我表示感谢。", "Tā duì wǒ biǎoshì gǎnxiè.", "Anh ấy bày tỏ sự cảm ơn đối với tôi.", "Động từ"],
    ["表扬", "biǎoyáng", "biểu dương, khen ngợi", "老师表扬了他。", "Lǎoshī biǎoyáng le tā.", "Giáo viên đã khen ngợi anh ấy.", "Động từ"],
    ["博士", "bóshì", "tiến sĩ", "他在读博士。", "Tā zài dú bóshì.", "Anh ấy đang học tiến sĩ.", "Danh từ"],
    ["部分", "bùfen", "phần, bộ phận", "这只是其中的一部分。", "Zhè zhǐshì qízhōng de yí bùfen.", "Đây chỉ là một phần trong đó.", "Danh từ"],
    ["擦", "cā", "lau, chùi", "请把桌子擦干净。", "Qǐng bǎ zhuōzi cā gānjìng.", "Xin hãy lau sạch bàn.", "Động từ"],
    ["猜", "cāi", "đoán", "你猜我刚才看到了谁？", "Nǐ cāi wǒ gāngcái kàndào le shéi?", "Bạn đoán xem vừa nãy tôi nhìn thấy ai?", "Động từ"],
    ["参观", "cānguān", "tham quan", "周末我们要去参观博物馆。", "Zhōumò wǒmen yào qù cānguān bówùguǎn.", "Cuối tuần chúng tôi sẽ đi tham quan viện bảo tàng.", "Động từ"],
    ["参加", "cānjiā", "tham gia", "你想参加什么活动？", "Nǐ xiǎng cānjiā shénme huódòng?", "Bạn muốn tham gia hoạt động gì?", "Động từ"],
    ["材料", "cáiliào", "tài liệu", "请准备好开会的材料。", "Qǐng zhǔnbèi hǎo kāihuì de cáiliào.", "Xin hãy chuẩn bị tốt tài liệu họp.", "Danh từ"]
  ],
"hsk14": [
    ["牙膏", "yágāo", "kem đánh răng", "早上刷牙的时候，牙膏用完了。", "Zǎoshang shuāyá de shíhou, yágāo yòng wán le.", "Buổi sáng lúc đánh răng, kem đánh răng đã dùng hết rồi.", "Danh từ"],
    ["牙刷", "yáshuā", "bàn chải", "医生建议三个月换一把新牙刷。", "Yīshēng jiànyì sān ge yuè huàn yì bǎ xīn yáshuā.", "Bác sĩ khuyên 3 tháng nên thay một chiếc bàn chải mới.", "Danh từ"],
    ["仓库", "cāngkù", "kho, nhà kho", "工人们正在仓库里搬运货物。", "Gōngrénmen zhèngzài cāngkù lǐ bānyùn huòwù.", "Các công nhân đang vận chuyển hàng hóa trong kho.", "Danh từ"],
    ["省", "shěng", "tiết kiệm", "乘坐地铁不仅快，还能省不少钱。", "Chéngzuò dìtiě bùjǐn kuài, hái néng shěng bù shǎo qián.", "Đi tàu điện ngầm không chỉ nhanh mà còn tiết kiệm được khá nhiều tiền.", "Động từ"],
    ["成本", "chéngběn", "chi phí", "我们要想办法降低生产成本。", "Wǒmen yào xiǎng bànfǎ jiàngdī shēngchǎn chéngběn.", "Chúng ta phải tìm cách giảm chi phí sản xuất.", "Danh từ"],
    ["污染", "wūrǎn", "ô nhiễm", "保护环境，减少塑料对海洋的污染。", "Bǎohù huánjìng, jiǎnshǎo sùliào duì hǎiyáng de wūrǎn.", "Bảo vệ môi trường, giảm thiểu ô nhiễm nhựa đối với đại dương.", "Động từ/Danh từ"],
    ["垃圾", "lājī", "rác", "请把垃圾扔进垃圾桶里。", "Qǐng bǎ lājī rēng jìn lājītǒng lǐ.", "Xin hãy vứt rác vào trong thùng rác.", "Danh từ"],
    ["脏", "zāng", "bẩn", "你的衣服脏了，快去换一件吧。", "Nǐ de yīfu zāng le, kuài qù huàn yí jiàn ba.", "Quần áo của bạn bẩn rồi, mau đi thay một bộ khác đi.", "Tính từ"],
    ["弄", "nòng", "làm, làm cho", "我不小心把裤子弄脏了。", "Wǒ bù xiǎoxīn bǎ kùzi nòng zāng le.", "Tôi không cẩn thận làm bẩn quần rồi.", "Động từ"],
    ["空", "kōng", "trống, rỗng", "这个瓶子是空的，里面什么也没有。", "Zhè ge píngzi shì kōng de, lǐmiàn shénme yě méiyǒu.", "Chiếc bình này trống rỗng, bên trong chẳng có gì cả.", "Tính từ"],
    ["盒子", "hézi", "hộp, cái hộp", "这个塑料盒子里装满了新鲜水果。", "Zhè ge sùliào hézi lǐ zhuāng mǎn le xīnxiān shuǐguǒ.", "Trong chiếc hộp nhựa này đựng đầy hoa quả tươi.", "Danh từ"],
    ["扔", "rēng", "vứt, bỏ", "不要随手扔废纸。", "Bú yào suíshǒu rēng fèizhǐ.", "Đừng tiện tay vứt giấy thải.", "Động từ"],
    ["速度", "sùdù", "tốc độ", "这辆车的行驶速度非常快。", "Zhè liàng chē de xíngshǐ sùdù fēicháng kuài.", "Tốc độ di chuyển của chiếc xe này rất nhanh.", "Danh từ"],
    ["既然", "jìrán", "vì (đã... thì)", "既然来了，就多玩几天吧。", "Jìrán lái le, jiù duō wán jǐ tiān ba.", "Đã đến rồi thì ở lại chơi thêm vài ngày đi.", "Liên từ"],
    ["地球", "dìqiú", "Trái Đất", "地球是我们共同的家园。", "Dìqiú shì wǒmen gòngtóng de jiāyuán.", "Trái Đất là ngôi nhà chung của chúng ta.", "Danh từ"],
    ["停", "tíng", "dừng, đỗ", "请把车停在指定的停车位上。", "Qǐng bǎ chē tíng zài zhǐdìng de tíngchēwèi shàng.", "Xin hãy đỗ xe ở chỗ đỗ xe quy định.", "Động từ"],
    ["得意", "déyì", "đắc ý, tự hào", "取得了这么好的成绩，他感到非常得意。", "Qǔdé le zhème hǎo de chéngjì, tā gǎndào fēicháng déyì.", "Đạt được thành tích tốt như vậy, anh ấy cảm thấy rất đắc ý.", "Tính từ"],
    ["目的", "mùdì", "mục đích", "我们这次会议的主要目的是讨论新项目。", "Wǒmen zhè cì huìyì de zhǔyào mùdì shì tǎolùn xīn xiàngmù。", "Mục đích chính của cuộc họp lần này của chúng ta là thảo luận về dự án mới.", "Danh từ"],
    ["项目", "xiàngmù", "dự án, hạng mục", "这个项目需要大家共同努力才能完成。", "Zhè ge xiàngmù xūyào dàjiā gòngtóng nǔlì cái néng wánchéng.", "Dự án này cần mọi người cùng nhau nǔ lực mới có thể hoàn thành.", "Danh từ"],
    ["出错", "chūcuò", "mắc lỗi, sai sót", "做事一定要仔细，尽量避免出错。", "Zuòshì yídìng yào zǐxì, jìnliàng bìmiǎn chūcuò.", "Làm việc nhất định phải cẩn thận, cố gắng hết sức tránh mắc lỗi.", "Động từ"],
    ["塑料袋", "sùliàodài", "túi nilon, túi nhựa", "去超市买东西最好自己带购物袋，少用塑料袋。", "Qù chāoshì mǎi dōngxi zuìhǎo zìjǐ dài gòuwùdài, shǎo yòng sùliàodài.", "Đi siêu thị mua đồ tốt nhất tự mang túi mua sắm, ít dùng túi nilon.", "Danh từ"],
    ["于是", "yúshì", "thế là, cho nên", "天气太热，于是我们决定去游泳。", "Tiānqì tài rè, yúshì wǒmen juédìng qù yóuyǒng.", "Thời tiết quá nóng, thế là chúng tôi quyết định đi bơi.", "Liên từ"],
    ["鼓励", "gǔlì", "cổ vũ, khuyến khích", "老师总是鼓励我们要勇敢面对困难。", "Lǎoshī zǒngshì gǔlì wǒmen yào yǒnggǎn miànduì kùnnan.", "Thầy cô luôn khuyến khích chúng tôi phải dũng cảm đối mặt khó khăn.", "Động từ/Danh từ"],
    ["拒绝", "jùjué", "từ chối", "他礼貌地拒绝了对方的要求。", "Tā lǐmào de jùjué le duìfāng de yāoqiú.", "Anh ấy đã lịch sự từ chối yêu cầu của đối phương.", "Động từ"],
    ["减少", "jiǎnshǎo", "giảm bớt", "为了减少污染，我们要多骑自行车。", "Wèile jiǎnshǎo wūrǎn, wǒmen yào duō qí zìxíngchē.", "Để giảm bớt ô nhiễm, chúng ta nên đi xe đạp nhiều hơn.", "Động từ"],
    ["乘坐", "chéngzuò", "đi, đáp (phương tiện)", "欢迎乘坐本次列车。", "Huānyíng chéngzuò běn cì lièchē.", "Chào mừng quý khách đi chuyến tàu này.", "Động từ"],
    ["丢", "diū", "ném, vứt, mất", "我不小心把钥匙弄丢了。", "Wǒ bù xiǎoxīn bǎ yàoshi nòng diū le.", "Tôi không cẩn thận làm mất chìa khóa rồi.", "Động từ"],
    ["垃圾桶", "lājītǒng", "thùng rác", "请把废纸扔进垃圾桶。", "Qǐng bǎ fèizhǐ rēng jìn lājītǒng.", "Xin hãy vứt giấy thải vào thùng rác.", "Danh từ"],
    ["美丽", "měilì", "đẹp, xinh đẹp", "这里的风景非常美丽。", "Zhèlǐ de fēngjǐng fēicháng měilì.", "Phong cảnh ở đây rất xinh đẹp.", "Tính từ"]
],
 "hsk15": [
    ["弹钢琴", "tán gāngqín", "chơi đàn dương cầm", "她每天都练习弹钢琴。", "Tā měitiān dōu liànxí tán gāngqín.", "Cô ấy mỗi ngày đều luyện tập chơi piano.", "Cụm động từ"],
    ["棒", "bàng", "xuất sắc", "你的表现真棒！", "Nǐ de biǎoxiàn zhēn bàng!", "Biểu hiện của bạn thật xuất sắc!", "Tính từ"],
    ["孙子", "sūnzi", "cháu nội trai", "他很疼爱自己的孙子。", "Tā hěn téng'ài zìjǐ de sūnzi.", "Ông ấy rất yêu thương cháu trai của mình.", "Danh từ"],
    ["孙女", "sūnnǚ", "cháu nội gái", "她有一个可爱的孙女。", "Tā yǒu yí ge kě'ài de sūnnǚ.", "Bà ấy có một người cháu gái dễ thương.", "Danh từ"],
    ["寒假", "hánjià", "kỳ nghỉ đông", "寒假你打算去哪儿玩？", "Hánjià nǐ dǎsuàn qù nǎr wán?", "Kỳ nghỉ đông bạn định đi đâu chơi?", "Danh từ"],
    ["暑假", "shǔjià", "nghỉ hè", "暑假快到了。", "Shǔjià kuài dào le.", "Kỳ nghỉ hè sắp đến rồi.", "Danh từ"],
    ["放暑假", "fàng shǔjià", "nghỉ hè", "七月份我们就要放暑假了。", "Qī yuèfèn wǒmen jiù yào fàng shǔjià le.", "Tháng 7 chúng tôi sẽ được nghỉ hè rồi.", "Cụm động từ"],
    ["父亲", "fùqīn", "cha, bố", "他的父亲是一位医生。", "Tā de fùqīn shì yí wèi yīshēng.", "Cha của anh ấy là một bác sĩ.", "Danh từ"],
    ["母亲", "mǔqīn", "mẫu thân", "我的母亲是一位老师。", "Wǒ de mǔqīn shì yí wèi lǎoshī.", "Mẹ của tôi là một giáo viên.", "Danh từ"],
    ["闹钟", "nàozhōng", "đồng hồ báo thức", "我定了一个七点的闹钟。", "Wǒ dìng le yí ge qī diǎn de nàozhōng.", "Tôi đã đặt một chiếc đồng hồ báo thức lúc 7 giờ.", "Danh từ"],
    ["响", "xiǎng", "kêu, reo, vang", "电话响了。", "Diànhuà xiǎng le.", "Điện thoại reo rồi.", "Động từ"],
    ["醒", "xǐng", "thức dậy", "他还没醒。", "Tā hái méi xǐng.", "Anh ấy vẫn chưa thức dậy.", "Động từ"],
    ["赶", "gǎn", "vội, gấp", "他正在赶去机场。", "Tā zhèngzài gǎn qù jīchǎng.", "Anh ấy đang vội ra sân bay.", "Động từ"],
    ["厕所", "cèsuǒ", "nhà wc", "请问厕所在哪里？", "Qǐngwèn cèsuǒ zài nǎlǐ?", "Xin hỏi nhà vệ sinh ở đâu?", "Danh từ"],
    ["批评", "pīpíng", "phê bình", "经理批评了他。", "Jīnglǐ pīpíng le tā.", "Giám đốc đã phê bình anh ấy.", "Động từ"],
    ["弄", "nòng", "làm, kiếm", "别把衣服弄脏了。", "Bié bǎ yīfu nòng zāng le.", "Đừng làm bẩn quần áo.", "Động từ"],
    ["管理", "guǎnlǐ", "quản lý", "他管理公司管理得很好。", "Tā guǎnlǐ gōngsī guǎnlǐ de hěn hǎo.", "Anh ấy quản lý công ty rất tốt.", "Động/Danh từ"],
    ["打针", "dǎzhēn", "tiêm", "小孩子害怕打针。", "Xiǎoháizi hàipà dǎzhēn.", "Trẻ em sợ tiêm thuốc.", "Động từ"],
    ["护士", "hùshi", "y tá", "她是一名护士。", "Tā shì yì míng hùshi.", "Cô ấy là một y tá.", "Danh từ"],
    ["错误", "cuòwù", "lỗi", "他承认了自己的错误。", "Tā chéngrèn le zìjǐ de cuòwù.", "Anh ấy đã thừa nhận lỗi lầm của mình.", "Danh/Tính từ"],
    ["犯", "fàn", "phạm", "千万别再犯错了。", "Qiānwàn bié zài fàncuò le.", "Nhất thiết đừng phạm lỗi nữa.", "Động từ"],
    ["听取", "tīngqǔ", "lắng nghe", "我们要多听取别人的意见。", "Wǒmen yào duō tīngqǔ biérén de yìjiàn.", "Chúng ta cần lắng nghe nhiều hơn ý kiến của người khác.", "Động từ"],
    ["操作", "cāozuò", "thao tác", "这个操作很简单。", "Zhège cāozuò hěn jiǎndān.", "Thao tác này rất đơn giản.", "Động/Danh từ"],
    ["系统", "xìtǒng", "hệ thống", "电脑系统需要更新。", "Diànnǎo xìtǒng xūyào gēngxīn.", "Hệ thống máy tính cần được cập nhật.", "Danh từ"],
    ["设备", "shèbèi", "thiết bị", "这家医院的设备很先进。", "Zhè jiā yīyuàn de shèbèi hěn xiānjìn.", "Thiết bị của bệnh viện này rất tiên tiến.", "Danh từ"],
    ["统计", "tǒngjì", "thống kê", "请把这个月的数据统计一下。", "Qǐng bǎ zhège yuè de shùjù tǒngjì yíxià.", "Xin hãy thống kê lại dữ liệu của tháng này.", "Động từ"],
    ["数据", "shùjù", "số liệu", "这些数据非常重要。", "Zhèxiē shùjù fēicháng zhòngyào.", "Những số liệu này vô cùng quan trọng.", "Danh từ"],
    ["表扬", "biǎoyáng", "biểu dương", "老师表扬了他。", "Lǎoshī biǎoyáng le tā.", "Giáo viên đã biểu dương anh ấy.", "Động từ"],
    ["千万", "qiānwàn", "nhất thiết phải", "千万别去！", "Qiānwàn bié qù!", "Tuyệt đối đừng đi!", "Phó từ"],
    ["怀疑", "huáiyí", "hoài nghi", "我怀疑他说谎。", "Wǒ huáiyí tā shuōhuǎng.", "Tôi hoài nghi anh ta nói dối.", "Động từ"],
    ["故意", "gùyì", "cố ý", "对不起，我不是故意的。", "Duìbùqǐ, wǒ bú shì gùyì de.", "Xin lỗi, tôi không cố ý.", "Phó từ"],
    ["敲", "qiāo", "gõ", "有人在敲门。", "Yǒurén zài qiāo mén.", "Có người đang gõ cửa.", "Động từ"],
    ["整理", "zhěnglǐ", "dọn dẹp, sắp xếp", "请整理一下房间。", "Qǐng zhěnglǐ yíxià fángjiān.", "Hãy dọn dẹp lại phòng một chút.", "Động từ"],
    ["合适", "héshì", "thích hợp", "这件衣服很合适。", "Zhè jiàn yīfu hěn héshì.", "Bộ quần áo này rất vừa vặn.", "Tính từ"],
    ["骗", "piàn", "lừa gạt", "你千万别骗我。", "Nǐ qiānwàn bié piàn wǒ.", "Tuyệt đối đừng lừa tôi.", "Động từ"],
    ["儿童", "értóng", "trẻ em", "这是给儿童看的书。", "Zhè shì gěi értóng kàn de shū.", "Đây là sách dành cho trẻ em đọc.", "Danh từ"],
    ["假", "jiǎ", "giả", "这个消息是假的。", "Zhège xiāoxi shì jiǎ de.", "Tin tức này là giả đấy.", "Tính từ"],
    ["左右", "zuǒyòu", "khoảng", "明天下午三点左右。", "Míngtiān xiàwǔ sān diǎn zuǒyòu.", "Khoảng 3 giờ chiều mai.", "Danh từ"],
    ["懒", "lǎn", "lười biếng", "他有点儿懒。", "Tā yǒudiǎnr lǎn.", "Cậu ấy hơi lười một chút.", "Tính từ"],
    ["笨", "bèn", "ngốc, vụng về", "我太笨了。", "Wǒ tài bèn le.", "Tôi ngốc quá.", "Tính từ"],
    ["粗心", "cūxīn", "cẩu thả, sơ ý", "考试时不能粗心。", "Kǎoshì shí bùnéng cūxīn.", "Khi thi không được cẩu thả.", "Tính từ"],
    ["骄傲", "jiāo'ào", "tự hào, kiêu ngạo", "父母为你感到骄傲。", "Fùmǔ wèi nǐ gǎndào jiāo'ào.", "Bố mẹ cảm thấy tự hào về bạn.", "Tính từ"],
    ["害羞", "hàixiū", "xấu hổ", "那个女孩很害羞。", "Nàge nǚhái hěn hàixiū.", "Cô bé đó rất e thẹn.", "Tính từ"]
],
  "hsk16": [
  ["博士", "bóshì", "tiến sĩ", "他在读博士。", "Tā zài dú bóshì.", "Anh ấy đang học tiến sĩ.", "Danh từ"],
  ["签证", "qiānzhèng", "visa, thị thực", "我明天要去办签证。", "Wǒ míngtiān yào qù bàn qiānzhèng.", "Ngày mai tôi phải đi làm visa.", "Danh từ"],
  ["报名", "bàomíng", "ghi danh, đăng ký", "我想报名参加这个课程。", "Wǒ xiǎng bàomíng cānjiā zhège kèchéng.", "Tôi muốn đăng ký tham gia khóa học này.", "Động từ"],
  ["表格", "biǎogé", "bảng biểu, bản kê khai", "请您填写这张表格。", "Qǐng nín tiánxiě zhè zhāng biǎogé.", "Xin ngài điền vào bản kê khai này.", "Danh từ"],
  ["传真", "chuánzhēn", "gửi fax, bản fax", "请把这份文件传真给他。", "Qǐng bǎ zhè fèn wénjiàn chuánzhēn gěi tā.", "Xin hãy fax tài liệu này cho anh ấy.", "Động từ/Danh từ"],
  ["登记", "dēngjì", "đăng ký (hộ kinh doanh, thủ tục...)", "请在这里登记您的个人信息。", "Qǐng zài zhèlǐ dēngjì nín de gèrén xìnxī.", "Xin hãy đăng ký thông tin cá nhân của ngài ở đây.", "Động từ"],
  ["传真机", "chuánzhēnjī", "máy fax", "办公室里有一台新的传真机。", "Bàngōngshì lǐ yǒu yì tái xīn de chuánzhēnjī.", "Trong văn phòng có một chiếc máy fax mới.", "Danh từ"],
  ["传真号码", "chuánzhēn hàomǎ", "số fax", "请问您的传真号码是多少？", "Qǐngwèn nín de chuánzhēn hàomǎ shì duōshao?", "Xin hỏi số fax của ngài là bao nhiêu?", "Danh từ"],
  ["电子邮件", "diànzǐ yóujiàn", "email, thư điện tử", "我给你发了一封电子邮件。", "Wǒ gěi nǐ fā le yì fēng diànzǐ yóujiàn.", "Tôi đã gửi cho bạn một email.", "Danh từ"],
  ["过期", "guòqī", "quá hạn, hết hạn", "这个面包已经过期了，不能吃。", "Zhège miànbāo yǐjīng guòqī le, bù néng chī.", "Cái bánh mì này đã hết hạn rồi, không thể ăn.", "Động từ"],
  ["号码", "hàomǎ", "số", "你的手机号码是多少？", "Nǐ de shǒujī hàomǎ shì duōshao?", "Số điện thoại di động của bạn là bao nhiêu?", "Danh từ"],
  ["参观", "cānguān", "tham quan, đi thăm", "明天我们要去参观博物馆。", "Míngtiān wǒmen yào qù cānguān bówùguǎn.", "Ngày mai chúng ta sẽ đi tham quan bảo tàng.", "Động từ"],
  ["激动", "jīdòng", "xúc động, kích động", "听到好消息，他激动得哭了。", "Tīngdào hǎo xiāoxi, tā jīdòng de kū le.", "Nghe được tin tốt, anh ấy xúc động đến phát khóc.", "Tính từ"],
  ["小伙子", "xiǎohuǒzi", "chàng trai", "那个小伙子长得很帅。", "Nàge xiǎohuǒzi zhǎng de hěn shuài.", "Chàng trai đó trông rất đẹp trai.", "Danh từ"],
  ["小姑娘", "xiǎogūniang", "cô gái nhỏ, tiểu cô nương", "这个小姑娘真可爱。", "Zhège xiǎogūniang zhēn kě'ài.", "Tiểu cô nương này thật đáng yêu.", "Danh từ"],
  ["记者", "jìzhě", "nhà báo, phóng viên", "她是一名新闻记者。", "Tā shì yì míng xīnwén jìzhě.", "Cô ấy là một phóng viên tin tức.", "Danh từ"],
  ["代表", "dàibiǎo", "đại diện, thay mặt", "他代表公司发言。", "Tā dàibiǎo gōngsī fāyán.", "Anh ấy đại diện cho công ty phát biểu.", "Động từ/Danh từ"],
  ["恐怕", "kǒngpà", "e rằng, có lẽ", "雨下得太大了，恐怕他不会来了。", "Yǔ xià de tài dà le, kǒngpà tā bú huì lái le.", "Mưa to quá, e rằng anh ấy sẽ không đến.", "Phó từ"],
  ["失望", "shīwàng", "thất vọng", "他的表现让我很失望。", "Tā de biǎoxiàn ràng wǒ hěn shīwàng.", "Sự thể hiện của anh ấy khiến tôi rất thất vọng.", "Tính từ/Động từ"],
  ["郊区", "jiāoqū", "vùng ngoại ô", "周末我们去郊区玩吧。", "Zhōumò wǒmen qù jiāoqū wán ba.", "Cuối tuần chúng ta đi vùng ngoại ô chơi nhé.", "Danh từ"],
  ["到底", "dàodǐ", "rốt cuộc (nhấn mạnh)", "你到底去不去？", "Nǐ dàodǐ qù bú qù?", "Rốt cuộc bạn có đi không?", "Phó từ"],
  ["呀", "ya", "nha, à, nhé (trợ từ)", "快点儿走呀！", "Kuài diǎnr zǒu ya!", "Đi nhanh lên nha!", "Trợ từ"],
  ["导游", "dǎoyóu", "hướng dẫn viên du lịch", "我们的导游非常热情。", "Wǒmen de dǎoyóu fēicháng rèqíng.", "Hướng dẫn viên du lịch của chúng tôi vô cùng nhiệt tình.", "Danh từ"],
  ["礼貌", "lǐmào", "lễ phép, lịch sự", "这个孩子对人很有礼貌。", "Zhège háizi duì rén hěn yǒu lǐmào.", "Đứa bé này đối với người khác rất lễ phép.", "Danh từ/Tính từ"],
  ["原谅", "yuánliàng", "tha thứ", "请原谅我的错误。", "Qǐng yuánliàng wǒ de cuòwù.", "Xin hãy tha thứ cho sai lầm của tôi.", "Động từ"],
  ["失恋", "shīliàn", "thất tình", "他最近失恋了，心情不好。", "Tā zuìjìn shīliàn le, xīnqíng bù hǎo.", "Dạo này anh ấy thất tình, tâm trạng không được tốt.", "Động từ"],
  ["失业", "shīyè", "thất nghiệp", "他因为公司倒闭而失业了。", "Tā yīnwèi gōngsī dǎobì ér shīyè le.", "Anh ấy vì công ty phá sản mà thất nghiệp rồi.", "Động từ"],
  ["失败", "shībài", "thất bại", "失败是成功之母。", "Shībài shì chénggōng zhī mǔ.", "Thất bại là mẹ thành công.", "Động từ/Danh từ"],
  ["坚持到底", "jiānchí dàodǐ", "kiên trì đến cùng", "无论多难，我们都要坚持到底。", "Wúlùn duō nán, wǒmen dōu yào jiānchí dàodǐ.", "Bất luận khó khăn đến đâu, chúng ta đều phải kiên trì đến cùng.", "Cụm từ"],
  ["挂", "guà", "treo, móc", "请把这幅画挂在墙上。", "Qǐng bǎ zhè fú huà guà zài qiáng shàng.", "Xin hãy treo bức tranh này lên tường.", "Động từ"],
  ["同情", "tóngqíng", "thông cảm, đồng tình", "大家都很同情他的遭遇。", "Dàjiā dōu hěn tóngqíng tā de zāoyù.", "Mọi người đều rất thông cảm với hoàn cảnh của anh ấy.", "Động từ"],
  ["推", "tuī", "hoãn lại, đẩy, triển khai", "请把门推开。", "Qǐng bǎ mén tuī kāi.", "Xin hãy đẩy cửa ra.", "Động từ"],
  ["预习", "yùxí", "chuẩn bị bài", "上课前我们要好好预习。", "Shàngkè qián wǒmen yào hǎohǎo yùxí.", "Trước khi lên lớp chúng ta phải chuẩn bị bài thật tốt.", "Động từ"],
  ["重点", "zhòngdiǎn", "trọng điểm, trọng tâm", "这是今天会议的重点。", "Zhè shì jīntiān huìyì de zhòngdiǎn.", "Đây là trọng tâm của cuộc họp hôm nay.", "Danh từ"],
  ["马虎", "mǎhu", "cẩu thả, lơ đễnh", "他做事总是很马虎。", "Tā zuòshì zǒngshì hěn mǎhu.", "Anh ấy làm việc luôn rất cẩu thả.", "Tính từ"],
  ["自信", "zìxìn", "tự tin", "她是一个非常自信的女孩。", "Tā shì yí ge fēicháng zìxìn de nǚhái.", "Cô ấy là một cô gái vô cùng tự tin.", "Tính từ"],
  ["冷静", "lěngjìng", "bình tĩnh, điềm tĩnh", "遇到危险时要保持冷静。", "Yùdào wēixiǎn shí yào bǎochí lěngjìng.", "Khi gặp nguy hiểm phải giữ bình tĩnh.", "Tính từ"],
  ["输", "shū", "thua", "这场比赛我们输了。", "Zhè chǎng bǐsài wǒmen shū le.", "Trận đấu này chúng tôi thua rồi.", "Động từ"],
  ["重视", "zhòngshì", "xem trọng, chú trọng", "公司很重视年轻人的培养。", "Gōngsī hěn zhòngshì niánqīng rén de péiyǎng.", "Công ty rất xem trọng việc bồi dưỡng người trẻ.", "Động từ"],
  ["敢", "gǎn", "dám", "你敢一个人走夜路吗？", "Nǐ gǎn yí ge rén zǒu yèlù ma?", "Bạn có dám đi đường đêm một mình không?", "Động từ"],
  ["尊重", "zūnzhòng", "tôn trọng", "人与人之间应该互相尊重。", "Rén yǔ rén zhījiān yīnggāi hùxiāng zūnzhòng.", "Giữa người với người nên tôn trọng lẫn nhau.", "Động từ"]
],
  "hsk17": [

  ["凉快", "liáng kuai", "mát mẻ", "晚上的天气很凉快。", "Wǎnshang de tiānqì hěn liángkuai.", "Thời tiết buổi tối rất mát mẻ.", "Tính từ"],
  ["倒", "dào", "rót (trà, nước...)", "我给你倒一杯水。", "Wǒ gěi nǐ dào yì bēi shuǐ.", "Để tôi rót cho bạn một cốc nước.", "Động từ"],
  ["热闹", "rè nao", "náo nhiệt", "这里的夜市很热闹。", "Zhèlǐ de yèshì hěn rènao.", "Chợ đêm ở đây rất náo nhiệt.", "Tính từ"],
  ["云", "yún", "mây", "天上的白云很漂亮。", "Tiānshàng de báiyún hěn piàoliang.", "Mây trắng trên trời rất đẹp.", "Danh từ"],
  ["广播", "guǎng bō", "chương trình phát thanh", "我每天早上听广播。", "Wǒ měitiān zǎoshang tīng guǎngbō.", "Mỗi sáng tôi đều nghe đài phát thanh.", "Danh từ"],
  ["毛", "máo", "lông", "这只小狗的毛很软。", "Zhè zhī xiǎogǒu de máo hěn ruǎn.", "Lông của chú chó này rất mềm.", "Danh từ"],
  ["抱", "bào", "bế, bồng, ôm", "妈妈抱着一个孩子。", "Māma bào zhe yí gè háizi.", "Mẹ đang bế một đứa trẻ.", "Động từ"],
  ["干", "gàn", "làm", "我们一起干吧！", "Wǒmen yìqǐ gàn ba!", "Chúng ta cùng làm nhé!", "Động từ"],
  ["严格", "yán gé", "nghiêm khắc, nghiêm ngặt", "老师对我们很严格。", "Lǎoshī duì wǒmen hěn yángé.", "Thầy giáo rất nghiêm khắc với chúng tôi.", "Tính từ"],
  ["难受", "nán shòu", "bực bội, buồn rầu", "我感冒了，身体很难受。", "Wǒ gǎnmào le, shēntǐ hěn nánshòu.", "Tôi bị cảm, người rất bực bội khó chịu.", "Tính từ"],
  ["干", "gān", "khô", "衣服已经干了。", "Yīfu yǐjīng gān le.", "Quần áo đã khô rồi.", "Danh từ/Tính từ"],
  ["干燥", "gān zào", "khô hanh", "秋天的天气很干燥。", "Qiūtiān de tiānqì hěn gānzào.", "Thời tiết mùa thu rất khô hanh.", "Tính từ"],
  ["湿", "shī", "ẩm ướt", "我的鞋子全湿了。", "Wǒ de xiézi quán shī le.", "Giày của tôi ướt hết rồi.", "Tính từ"],
  ["经过", "jīng guò", "trải qua (+ sự việc)", "经过努力，他成功了。", "Jīngguò nǔlì, tā chénggōng le.", "Trải qua nỗ lực, anh ấy đã thành công.", "Động từ/Giới từ"],
  ["去过", "qù guò", "đi qua, từng đến (+ địa điểm)", "我去过北京。", "Wǒ qù guò Běijīng.", "Tôi đã từng đến Bắc Kinh.", "Động từ"],
  ["趟", "tàng", "chuyến (xe/đi)", "我去了一趟超市。", "Wǒ qù le yí tàng chāoshì.", "Tôi đã đi siêu thị một chuyến.", "Lượng từ"],
  ["躺", "tǎng", "nằm", "他躺在床上看书。", "Tā tǎng zài chuáng shàng kàn shū.", "Anh ấy nằm trên giường đọc sách.", "Động từ"],
  ["放暑假", "fàng shǔ jià", "nghỉ hè", "我们下个月放暑假。", "Wǒmen xià gè yuè fàng shǔjià.", "Tháng sau chúng tôi nghỉ hè.", "Động từ"],
  ["老虎", "lǎo hǔ", "hổ", "森林里有一只老虎。", "Sēnlín lǐ yǒu yì zhī lǎohǔ.", "Trong rừng có một con hổ.", "Danh từ"],
  ["入口", "rù kǒu", "cổng vào, lối vào", "超市的入口在哪里？", "Chāoshì de rùkǒu zài nǎlǐ?", "Lối vào siêu thị ở đâu?", "Danh từ"],
  ["出口", "chū kǒu", "lối ra", "请从这个出口出去。", "Qǐng cóng zhège chūkǒu chūqù.", "Vui lòng đi ra từ lối ra này.", "Danh từ"],
  ["排队", "pái duì", "xếp hàng", "大家正在排队买票。", "Dàjiā zhèngzài páiduì mǎi piào.", "Mọi người đang xếp hàng mua vé.", "Động từ"],
  ["活泼", "huó pō", "hoạt bát, nhanh nhẹn", "这个孩子很活泼。", "Zhège háizi hěn huópō.", "Đứa trẻ này rất hoạt bát.", "Tính từ"],
  ["六一儿童节", "liù yī ér tóng jié", "ngày Quốc tế thiếu nhi", "祝你六一儿童节快乐！", "Zhù nǐ liù yī értóng jié kuàilè!", "Chúc bạn ngày Quốc tế thiếu nhi vui vẻ!", "Danh từ"],
  ["社会", "shè huì", "xã hội", "我们生活在现代社会。", "Wǒmen shēnghuó zài xiàndài shèhuì.", "Chúng ta sống trong xã hội hiện đại.", "Danh từ"],
  ["社牛", "shè niú", "giỏi giao tiếp", "他是个真正的社牛。", "Tā shì gè zhēnzhèng de shèniú.", "Anh ấy là một người giỏi giao tiếp thực sự.", "Danh từ"],
  ["社恐", "shè kǒng", "ngại giao tiếp", "我有点社恐，不爱去人多的地方。", "Wǒ yǒudiǎn shèkǒng, bú ài qù rén duō de dìfang.", "Tôi hơi ngại giao tiếp, không thích đến nơi đông người.", "Danh từ"],
  ["竞争", "jìng zhēng", "cạnh tranh", "现在的职场竞争很激烈。", "Xiànzài de zhíchǎng jìngzhēng hěn jīliè.", "Cạnh tranh chốn công sở hiện nay rất khốc liệt.", "Động từ/Danh từ"],
  ["激烈", "jī liè", "khốc liệt, kịch liệt", "比赛进行得非常激烈。", "Bǐsài jìnxíng de fēicháng jīliè.", "Trận đấu diễn ra vô cùng khốc liệt.", "Tính từ"],
  ["森林", "sēn lín", "rừng rậm", "森林里有很多树。", "Sēnlín lǐ yǒu hěn duō shù.", "Trong rừng rậm có rất nhiều cây.", "Danh từ"],
  ["剩", "shèng", "dư thừa", "饭菜还剩很多。", "Fàncài hái shèng hěn duō.", "Đồ ăn vẫn còn dư nhiều.", "Động từ/Tính từ"],
  ["剩菜", "shèng cài", "món ăn thừa", "我把剩菜放在冰箱里。", "Wǒ bǎ shèngcài fàng zài bīngxiāng lǐ.", "Tôi cất đồ ăn thừa vào tủ lạnh.", "Danh từ"],
  ["剩下", "shèng xià", "phần còn lại", "剩下的交给我吧。", "Shèngxià de jiāo gěi wǒ ba.", "Phần còn lại cứ giao cho tôi.", "Động từ"],
  ["海洋", "hǎi yáng", "biển, đại dương", "海洋里有很多鱼。", "Hǎiyáng lǐ yǒu hěn duō yú.", "Dưới đại dương có rất nhiều cá.", "Danh từ"],
  ["底", "dǐ", "đáy", "杯子底有一个洞。", "Bēizi dǐ yǒu yí gè dòng.", "Đáy cốc có một cái lỗ.", "Danh từ"],
  ["美人鱼", "měi rén yú", "mỹ nhân ngư", "你相信有美人鱼吗？", "Nǐ xiāngxìn yǒu měirényú ma?", "Bạn có tin là có mỹ nhân ngư không?", "Danh từ"],
  ["公里", "gōng lǐ", "km (kilomet)", "我家离学校三公里。", "Wǒ jiā lí xuéxiào sān gōnglǐ.", "Nhà tôi cách trường ba kilomet.", "Lượng từ"],
  ["仍然", "réng rán", "vẫn", "天黑了，他仍然在学习。", "Tiān hēi le, tā réngrán zài xuéxí.", "Trời tối rồi, anh ấy vẫn đang học.", "Phó từ"],
  ["排列", "pái liè", "sắp xếp (theo thứ tự)", "请按照时间顺序排列这些材料。", "Qǐng ànzhào shíjiān shùnxù páiliè zhèxiē cáiliào.", "Sắp xếp tài liệu này theo thời gian.", "Động từ"],
  ["梦", "mèng", "giấc mơ", "我昨晚做了一个好梦。", "Wǒ zuówǎn zuò le yí gè hǎo mèng.", "Tối qua tôi đã có một giấc mơ đẹp.", "Danh từ/Động từ"],
  ["按照", "àn zhào", "dựa theo, theo", "我们按照计划进行。", "Wǒmen ànzhào jìhuà jìnxíng.", "Chúng ta tiến hành dựa theo kế hoạch.", "Giới từ"],
  ["顺序", "shùn xù", "trình tự", "请按顺序排队。", "Qǐng àn shùnxù páiduì.", "Vui lòng xếp hàng theo trình tự.", "Danh từ"],
  ["做白日梦", "zuò bái rì mèng", "nằm mơ giữa ban ngày", "别做白日梦了，快工作！", "Bié zuò bái rì mèng le, kuài gōngzuò!", "Đừng nằm mơ giữa ban ngày nữa, mau làm việc đi!", "Cụm động từ"]
  ],
  "hsk18": [
  ["降落", "jiàngluò", "đáp xuống, hạ cánh", "飞机马上就要降落了。", "Fēijī mǎshàng jiù yào jiàngluò le.", "Máy bay sắp sửa hạ cánh rồi.", "Động từ"],
  ["火", "huǒ", "chạy, đắt, được nhiều người ưa chuộng", "这家餐厅现在很火。", "Zhè jiā cāntīng xiànzài hěn huǒ.", "Nhà hàng này bây giờ rất được ưa chuộng.", "Tính từ"],
  ["作者", "zuòzhě", "tác giả", "这本书的作者是谁？", "Zhè běn shū de zuòzhě shì shéi?", "Tác giả của cuốn sách này là ai?", "Danh từ"],
  ["交通", "jiāotōng", "giao thông, thông tin liên lạc", "这里的交通很方便。", "Zhèlǐ de jiāotōng hěn fāngbiàn.", "Giao thông ở đây rất thuận tiện.", "Danh từ"],
  ["技术", "jìshù", "kỹ thuật, công nghệ", "现代技术发展得很快。", "Xiàndài jìshù fāzhǎn de hěn kuài.", "Công nghệ hiện đại phát triển rất nhanh.", "Danh từ"],
  ["是否", "shìfǒu", "hay không", "我不知道他是否同意。", "Wǒ bù zhīdào tā shìfǒu tóngyì.", "Tôi không biết anh ấy có đồng ý hay không.", "Phó từ"],
  ["秒", "miǎo", "giây", "请等我几秒钟。", "Qǐng děng wǒ jǐ miǎo zhōng.", "Xin đợi tôi vài giây.", "Lượng từ"],
  ["方式", "fāngshì", "phương thức, cách thức", "每个人有自己的生活方式。", "Měi gè rén yǒu zìjǐ de shēnghuó fāngshì.", "Mỗi người có một cách sống riêng.", "Danh từ"],
  ["受不了", "shòubuliǎo", "chịu không nổi, chịu không được", "天气太热了，我受不了。", "Tiānqì tài rè le, wǒ shòubuliǎo.", "Thời tiết nóng quá, tôi chịu không nổi.", "Động từ"],
  ["日记", "rìjì", "nhật ký", "她每天都写日记。", "Tā měitiān dōu xiě rìjì.", "Cô ấy viết nhật ký mỗi ngày.", "Danh từ"],
  ["安全", "ānquán", "an toàn", "晚上一个人出门不安全。", "Wǎnshang yí gè rén chūmén bù ānquán.", "Buổi tối ra ngoài một mình không an toàn.", "Tính từ"],
  ["密码", "mìmǎ", "mật mã", "我忘记了我的银行密码。", "Wǒ wàngjì le wǒ de yínháng mìmǎ.", "Tôi quên mất mật khẩu ngân hàng của mình rồi.", "Danh từ"],
  ["允许", "yǔnxǔ", "cho phép", "这里不允许抽烟。", "Zhèlǐ bù yǔnxǔ chōuyān.", "Ở đây không cho phép hút thuốc.", "Động từ"],
  ["座", "zuò", "tòa, hòn, cây (dùng cho cầu, núi, cao ốc...)", "这座桥很长。", "Zhè zuò qiáo hěn cháng.", "Cây cầu này rất dài.", "Lượng từ"],
  ["桥", "qiáo", "cầu", "我们在桥上走。", "Wǒmen zài qiáo shàng zǒu.", "Chúng tôi đi bộ trên cầu.", "Danh từ"],
  ["危险", "wēixiǎn", "nguy hiểm", "这个地方很危险。", "Zhège dìfāng hěn wēixiǎn.", "Nơi này rất nguy hiểm.", "Tính từ"],
  ["接着", "jiēzhe", "ngay sau đó", "吃完饭，接着他去学习了。", "Chī wán fàn, jiēzhe tā qù xuéxí le.", "Ăn cơm xong, ngay sau đó anh ấy đi học.", "Phó từ"],
  ["警察", "jǐngchá", "cảnh sát", "他想当一名警察。", "Tā xiǎng dāng yì míng jǐngchá.", "Anh ấy muốn trở thành một cảnh sát.", "Danh từ"],
  ["抓", "zhuā", "bắt, túm", "警察抓住了小偷。", "Jǐngchá zhuā zhù le xiǎotōu.", "Cảnh sát đã bắt được tên trộm.", "Động từ"],
  ["咸", "xián", "mặn", "这道菜太咸了。", "Zhè dào cài tài xián le.", "Món ăn này mặn quá.", "Tính từ"],
  ["矿泉水", "kuàngquánshuǐ", "nước suối", "请给我一瓶矿泉水。", "Qǐng gěi wǒ yì píng kuàngquánshuǐ.", "Xin cho tôi một chai nước suối.", "Danh từ"],
  ["付款", "fù kuǎn", "trả tiền", "请问在哪里付款？", "Qǐng wèn zài nǎlǐ fù kuǎn?", "Xin hỏi trả tiền ở đâu?", "Động từ"],
  ["举", "jǔ", "nêu, đưa ra", "老师举了一个例子。", "Lǎoshī jǔ le yí gè lìzi.", "Giáo viên đã nêu ra một ví dụ.", "Động từ"],
  ["迷路", "mí lù", "lạc đường", "昨天我在森林里迷路了。", "Zuótiān wǒ zài sēnlín lǐ mí lù le.", "Hôm qua tôi bị lạc đường trong rừng.", "Động từ"],
  ["地址", "dìzhǐ", "địa chỉ", "请把你的地址发给我。", "Qǐng bǎ nǐ de dìzhǐ fā gěi wǒ.", "Vui lòng gửi địa chỉ của bạn cho tôi.", "Danh từ"],
  ["地点", "dìdiǎn", "địa điểm, nơi", "开会的地点在二楼。", "Kāihuì de dìdiǎn zài èr lóu.", "Địa điểm họp ở tầng hai.", "Danh từ"],
  ["世纪", "shìjì", "thế kỷ", "我们生活在二十一世纪。", "Wǒmen shēnghuó zài èrshíyī shìjì.", "Chúng ta đang sống ở thế kỷ 21.", "Danh từ"],
  ["邮局", "yóujú", "bưu điện", "邮局在银行的旁边。", "Yóujú zài yínháng de pángbiān.", "Bưu điện nằm ở bên cạnh ngân hàng.", "Danh từ"],
  ["收", "shōu", "nhận", "我收到了他的信。", "Wǒ shōu dào le tā de xìn.", "Tôi đã nhận được thư của anh ấy.", "Động từ"],
  ["信封", "xìnfēng", "phong thư, bì thư", "把信装进信封里。", "Bǎ xìn zhuāng jìn xìnfēng lǐ.", "Đút thư vào trong phong thư.", "Danh từ"],
  ["网站", "wǎngzhàn", "trang web", "这个网站很有用。", "Zhège wǎngzhàn hěn yǒuyòng.", "Trang web này rất hữu ích.", "Danh từ"],
  ["信息", "xìnxī", "tin tức, thông tin", "我在网上查了一些信息。", "Wǒ zài wǎng shàng chá le yìxiē xìnxī.", "Tôi đã tra cứu một số thông tin trên mạng.", "Danh từ"]
  ],
  "hsk19": [
    ["骗", "piàn", "lừa gạt", "你别骗我了。", "Nǐ bié piàn wǒ le.", "Bạn đừng lừa tôi nữa.", "Động từ"],
    ["乒乓球", "pīngpāngqiú", "bóng bàn", "下午我们去打乒乓球吧。", "Xiàwǔ wǒmen qù dǎ pīngpāngqiú ba.", "Chiều nay chúng ta đi đánh bóng bàn nhé.", "Danh từ"],
    ["破", "pò", "rách, vỡ", "我的杯子破了。", "Wǒ de bēizi pò le.", "Cái cốc của tôi vỡ rồi.", "Tính từ/Động từ"],
    ["千万", "qiānwàn", "nhất thiết, bằng mọi giá", "你千万别告诉别人。", "Nǐ qiānwàn bié gàosu biérén.", "Bạn nhất thiết đừng nói cho người khác biết.", "Phó từ"],
    ["敲", "qiāo", "gõ", "有人在敲门。", "Yǒurén zài qiāo mén.", "Có người đang gõ cửa.", "Động từ"],
    ["桥", "qiáo", "cây cầu", "河上有一座石桥。", "Hé shàng yǒu yí zuò shíqiáo.", "Trên sông có một cây cầu đá.", "Danh từ"],
    ["请客", "qǐngkè", "mời khách, đãi", "今天发工资了，我请客！", "Jīntiān fā gōngzī le, wǒ qǐngkè!", "Hôm nay phát lương rồi, tôi mời!", "Động từ"],
    ["然而", "rán'ér", "tuy nhiên, nhưng", "他虽然失败了，然而并没有放弃。", "Tā suīrán shībài le, rán'ér bìng méiyǒu fàngqì.", "Mặc dù anh ấy thất bại, tuy nhiên không hề từ bỏ.", "Liên từ"],
    ["让", "ràng", "nhường, bảo, để", "请让一下，我要过去。", "Qǐng ràng yíxià, wǒ yào guòqù.", "Xin nhường một chút, tôi muốn đi qua.", "Động từ"],
    ["热闹", "rènao", "náo nhiệt", "过年时街上非常热闹。", "Guònián shí jiē shàng fēicháng rènao.", "Lúc đón tết trên phố vô cùng náo nhiệt.", "Tính từ"],
    ["扔", "rēng", "ném, vứt", "请把垃圾扔掉。", "Qǐng bǎ lājī rēng diào.", "Xin hãy vứt rác đi.", "Động từ"],
    ["仍然", "réngrán", "vẫn", "虽然下雨，他仍然坚持去跑步。", "Suīrán xiàyǔ, tā réngrán jiānchí qù pǎobù.", "Mặc dù trời mưa, anh ấy vẫn kiên trì đi chạy bộ.", "Phó từ"],
    ["日记", "rìjì", "nhật ký", "她每天都有写日记的习惯。", "Tā měitiān dōu yǒu xiě rìjì de xíguàn.", "Cô ấy mỗi ngày đều có thói quen viết nhật ký.", "Danh từ"],
    ["软", "ruǎn", "mềm", "这块蛋糕很软。", "Zhè kuài dàngāo hěn ruǎn.", "Miếng bánh kem này rất mềm.", "Tính từ"],
    ["森林", "sēnlín", "rừng rậm", "这片森林里有很多动物。", "Zhè piàn sēnlín lǐ yǒu hěn duō dòngwù.", "Trong khu rừng này có rất nhiều động vật.", "Danh từ"],
    ["社会", "shèhuì", "xã hội", "我们要适应社会的发展。", "Wǒmen yào shìyìng shèhuì de fāzhǎn.", "Chúng ta phải thích nghi với sự phát triển của xã hội.", "Danh từ"],
    ["申请", "shēnqǐng", "xin, đăng ký", "我准备申请一份新工作。", "Wǒ zhǔnbèi shēnqǐng yí fèn xīn gōngzuò.", "Tôi chuẩn bị xin một công việc mới.", "Động từ"],
    ["省", "shěng", "tỉnh, tiết kiệm", "坐地铁能省很多时间。", "Zuò dìtiě néng shěng hěn duō shíjiān.", "Đi tàu điện ngầm có thể tiết kiệm rất nhiều thời gian.", "Danh từ/Động từ"],
    ["剩", "shèng", "thừa lại", "饭菜还剩很多。", "Fàncài hái shèng hěn duō.", "Cơm canh vẫn còn thừa lại rất nhiều.", "Động từ"],
    ["失望", "shīwàng", "thất vọng", "他的表现让我很失望。", "Tā de biǎoxiàn ràng wǒ hěn shīwàng.", "Sự thể hiện của anh ấy làm tôi rất thất vọng.", "Tính từ"],
    ["十分", "shífēn", "mười phần, vô cùng", "我对这个结果十分满意。", "Wǒ duì zhège jiéguǒ shífēn mǎnyì.", "Tôi vô cùng hài lòng với kết quả này.", "Phó từ"],
    ["实际", "shíjì", "thực tế", "理论必须联系实际。", "Lǐlùn bìxū liánxì shíjì.", "Lý luận bắt buộc phải liên hệ với thực tế.", "Danh từ/Tính từ"],
    ["实在", "shízài", "thực sự", "他实在太累了。", "Tā shízài tài lèi le.", "Anh ấy thực sự quá mệt rồi.", "Phó từ"],
    ["世纪", "shìjì", "thế kỷ", "我们生活在21世纪。", "Wǒmen shēnghuó zài 21 shìjì.", "Chúng ta sống ở thế kỷ 21.", "Danh từ"],
    ["是否", "shìfǒu", "có hay không", "你是否同意我的看法？", "Nǐ shìfǒu tóngyì wǒ de kànfǎ?", "Bạn có đồng ý với cách nhìn của tôi không?", "Phó từ"]
  ],
  "hsk20": [
    ["收", "shōu", "thu, nhận", "我已经收到了你的信。", "Wǒ yǐjīng shōu dào le nǐ de xìn.", "Tôi đã nhận được thư của bạn rồi.", "Động từ"],
    ["收拾", "shōushi", "dọn dẹp", "请把桌子收拾一下。", "Qǐng bǎ zhuōzi shōushi yíxià.", "Xin hãy dọn dẹp bàn một chút.", "Động từ"],
    ["受不了", "shòubuliǎo", "chịu không nổi", "这里的天气太热了，我受不了。", "Zhèlǐ de tiānqì tài rè le, wǒ shòubuliǎo.", "Thời tiết ở đây nóng quá, tôi chịu không nổi.", "Cụm động từ"],
    ["输", "shū", "thua", "这场比赛我们输了。", "Zhè chǎng bǐsài wǒmen shū le.", "Trận đấu này chúng tôi thua rồi.", "Động từ"],
    ["数量", "shùliàng", "số lượng", "这种产品的数量有限。", "Zhè zhǒng chǎnpǐn de shùliàng yǒuxiàn.", "Số lượng của sản phẩm này có hạn.", "Danh từ"],
    ["速度", "sùdù", "tốc độ", "他开车的速度很快。", "Tā kāichē de sùdù hěn kuài.", "Tốc độ lái xe của anh ấy rất nhanh.", "Danh từ"],
    ["酸", "suān", "chua", "这个苹果太酸了。", "Zhège píngguǒ tài suān le.", "Quả táo này chua quá.", "Tính từ"],
    ["孙子", "sūnzi", "cháu nội", "爷爷很疼爱他的小孙子。", "Yéye hěn téng'ài tā de xiǎo sūnzi.", "Ông nội rất thương yêu đứa cháu nội nhỏ của mình.", "Danh từ"],
    ["抬", "tái", "khiêng, nâng", "把头抬起来。", "Bǎ tóu tái qǐlái.", "Nâng đầu lên.", "Động từ"],
    ["弹钢琴", "tán gāngqín", "đánh piano", "她的爱好是弹钢琴。", "Tā de àihào shì tán gāngqín.", "Sở thích của cô ấy là đánh piano.", "Cụm động từ"],
    ["汤", "tāng", "canh", "这碗汤真好喝。", "Zhè wǎn tāng zhēn hǎohē.", "Bát canh này thật sự rất ngon.", "Danh từ"],
    ["趟", "tàng", "chuyến (lượng từ đi lại)", "我明天要去一趟北京。", "Wǒ míngtiān yào qù yí tàng Běijīng.", "Ngày mai tôi phải đi một chuyến Bắc Kinh.", "Lượng từ"],
    ["同情", "tóngqíng", "đồng tình, thông cảm", "我很同情他的遭遇。", "Wǒ hěn tóngqíng tā de zāoyù.", "Tôi rất thông cảm với hoàn cảnh của anh ấy.", "Động từ/Danh từ"],
    ["推", "tuī", "đẩy", "请把门推开。", "Qǐng bǎ mén tuī kāi.", "Xin hãy đẩy cửa ra.", "Động từ"],
    ["脱", "tuō", "cởi (quần áo, giày)", "太热了，我把外套脱了。", "Tài rè le, wǒ bǎ wàitào tuō le.", "Nóng quá, tôi cởi áo khoác ra rồi.", "Động từ"],
    ["网站", "wǎngzhàn", "trang web", "这是一个学习汉语的网站。", "Zhè shì yí ge xuéxí Hànyǔ de wǎngzhàn.", "Đây là một trang web học tiếng Hán.", "Danh từ"],
    ["往", "wǎng", "hướng về", "一直往前走就到了。", "Yìzhí wǎng qián zǒu jiù dào le.", "Cứ đi thẳng về phía trước là tới.", "Giới từ"],
    ["卫生间", "wèishēngjiān", "nhà vệ sinh", "请问卫生间在哪里？", "Qǐngwèn wèishēngjiān zài nǎlǐ?", "Xin hỏi nhà vệ sinh ở đâu?", "Danh từ"],
    ["温度", "wēndù", "nhiệt độ", "今天室外的温度是30度。", "Jīntiān shìwài de wēndù shì 30 dù.", "Nhiệt độ ngoài trời hôm nay là 30 độ.", "Danh từ"],
    ["文章", "wénzhāng", "bài văn", "这篇文章写得很好。", "Zhè piān wénzhāng xiě de hěn hǎo.", "Bài văn này viết rất hay.", "Danh từ"],
    ["咸", "xián", "mặn", "这个汤太咸了。", "Zhège tāng tài xián le.", "Canh này mặn quá.", "Tính từ"],
    ["相同", "xiāngtóng", "giống nhau", "我们俩的看法完全相同。", "Wǒmen liǎ de kànfǎ wánquán xiāngtóng.", "Cách nhìn của hai chúng tôi hoàn toàn giống nhau.", "Tính từ"],
    ["香", "xiāng", "thơm", "这朵花真香。", "Zhè duǒ huā zhēn xiāng.", "Bông hoa này thật thơm.", "Tính từ"],
    ["详细", "xiángxì", "chi tiết", "请把经过详细地说一遍。", "Qǐng bǎ jīngguò xiángxì de shuō yí biàn.", "Xin hãy nói lại chi tiết quá trình.", "Tính từ"],
    ["响", "xiǎng", "kêu, vang", "你的手机响了。", "Nǐ de shǒujī xiǎng le.", "Điện thoại của bạn kêu kìa.", "Động từ"]
  ]
};

const HSK_DATA = Object.fromEntries(Object.entries(_HSK_RAW).map( ([k,v]) => [k, v.map( ([hanzi,pinyin,meaning,ex_hanzi,ex_pinyin,ex_viet,tu_loai]) => ({
    hanzi,
    pinyin,
    meaning,
    ex_hanzi,
    ex_pinyin,
    ex_viet,
    tu_loai
}))]));

if (typeof module !== "undefined")
    module.exports = {
        HSK_DATA
    };
